(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<Local`QFTToolKit`
QCDBaseIndices


DefineTensorShortcuts[{{\[Phi],v,Y,T,\[Tau],U,D,W,\[Lambda],\[Alpha],g,\[Nu],t,U,\[CapitalSigma],m,Q,j},1},{{\[Phi],v,\[Tau],Q,d,u,m,\[Nu],e,t,U,Z,g,D,\[Psi],h,V,j},2},{{\[Lambda],Q,U,D,J,t,g,q,\[ScriptCapitalM],M,j},3},{{U,q,\[ScriptCapitalM],T},4}]
\[Pi]u[i_]:=Tensor[\[Pi],{i},{Void}](*Not DefineTensorShortcuts definable.*)
\[Pi]d[i_]:=Tensor[\[Pi],{Void},{i}]




