(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<Local`QFTToolKit`
Put[SaveFile=NBname["stub"]<>".out"]


ku[i_]:=T[ Subscript[k, i],"u"][\[Mu]];
kd[i_]:=T[ Subscript[k, i],"d"][\[Mu]];
ku0[i_]:=T[ Subscript[k, i],"u"][timespace@0];
kd0[i_]:=T[ Subscript[k, i],"d"][timespace@0];
ku1[i_]:=T[ Subscript[k, i],"u"][timespace@1];
kd1[i_]:=T[ Subscript[k, i],"d"][timespace@1];
(*Useful definitions*)
dkscalar:=d[k_]->k^2 d[\[CapitalOmega][k]]d[k];
IntOp2DifForm:=IntegralOp[a_,b_]:>(Apply[Times,d[First[#]]&/@a])b;



