BrowserCategory["Tensorial 4.0 Docs", None,
{Item["Introduction", "TIntroduction.nb", CopyTag -> None],
 BrowserCategory["Using Tensorial", None,
  {Item["Tensorial Basics","TTensorialBasics.nb", CopyTag -> None],
   Item["Output Format","TOutputFormat.nb", CopyTag -> None],
   Item["Customizing Tensorial","TCustomizingTensorial.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Examples", None,
  {Item["Flat and Curved","TFlatAndCurved.nb", CopyTag -> None],
   Item["Oblique Coordinates","TExample1.nb", CopyTag -> None],
   Item["Arrays & Tensors","TExample2.nb", CopyTag -> None],
   Item["Maxwell in Schwarzschild","TExample4.nb", CopyTag -> None],
   Item["Dirac Equation","TExample5.nb", CopyTag -> None],
   Item["Continuum Mechanics","TExample6.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Tensors & Format", None,
  {Item["Tensor","TTensor.nb", CopyTag -> None],
   Item["Void","TVoid.nb", CopyTag -> None],
   Item["UnnestTensor","TUnnestTensor.nb", CopyTag -> None],
   Item["SetDerivativeSymbols","TSetDerivativeSymbols.nb", CopyTag -> None],
   Item["SetPartialDisplay","TSetPartialDisplay.nb", CopyTag -> None],
   Item["SetCovariantDisplay","TSetCovariantDisplay.nb", CopyTag -> None],
   Item["SetLieDisplay","TSetLieDisplay.nb", CopyTag -> None],
   Item["TensorLabelFormat","TTensorLabelFormat.nb", CopyTag -> None],
   Item["ClearTensorLabelFormat","TTensorLabelFormat.nb", CopyTag -> None]}],

 BrowserCategory["Tensors Shortcuts", None,
  {Item["DefineTensorShortcuts","TDefineTensorShortcuts.nb", CopyTag -> None],
   Item["ClearTensorShortcuts","TClearTensorShortcuts.nb", CopyTag -> None],
   Item["TensorLabelFormat","TTensorLabelFormat.nb", CopyTag -> None]}],

 BrowserCategory["Tensor Values", None,
  {Item["SetTensorValues","TSetTensorValues.nb", CopyTag -> None],
   Item["SetTensorValueRules","TSetTensorValueRules.nb", CopyTag -> None],
   Item["TensorValueRules","TTensorValueRules.nb", CopyTag -> None],
   Item["ClearTensorValues","TClearTensorValues.nb", CopyTag -> None],
   Item["NonzeroValueRules","TNonzeroValueRules.nb", CopyTag -> None],
   Item["SelectedTensorRules","TSelectedTensorRules.nb", CopyTag -> None],
   Item["DeclareZeroTensor","TDeclareZeroTensor.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Base Indices", None,
  {Item["BaseIndices","TBaseIndices.nb", CopyTag -> None],
   Item["CompleteBaseIndices","TCompleteBaseIndices.nb", CopyTag -> None],
   Item["DeclareBaseIndices","TDeclareBaseIndices.nb", CopyTag -> None],
   Item["NDim","TNDim.nb", CopyTag -> None],
   Item["GetBaseIndices","TGetBaseIndices.nb", CopyTag -> None],
   Item["BaseIndexQ","TBaseIndexQ.nb", CopyTag -> None]}],

 BrowserCategory["Index Routines", None,
  {Item["ParseTermIndices","TParseTermIndices.nb", CopyTag -> None],
   Item["IndexParsingRules","TIndexParsingRules.nb", CopyTag -> None],
   Item["ExtractFreeIndices","TExtractFreeIndices.nb", CopyTag -> None],
   Item["SymbolicIndexQ","TSymbolicIndexQ.nb", CopyTag -> None],
   Item["RawIndex","TRawIndex.nb", CopyTag -> None],
   Item[Delimiter],
   Item["RaiseIndex","TRaiseIndex.nb", CopyTag -> None],
   Item["LowerIndex","TLowerIndex.nb", CopyTag -> None],
   Item["ReplaceIndex","TReplaceIndex.nb", CopyTag -> None],
   Item[Delimiter],
   Item["IndexChange","TIndexChange.nb", CopyTag -> None],
   Item["NewIndexChangePatterns","TNewIndexChangePatterns.nb", CopyTag -> None],
   Item["UpDownSwap","TUpDownSwap.nb", CopyTag -> None]}],

 BrowserCategory["Index Flavors", None,
  {Item["IndexFlavors","TIndexFlavors.nb", CopyTag -> None],
   Item["DeclareIndexFlavor","TDeclareIndexFlavor.nb", CopyTag -> None],
   Item["ClearIndexFlavor","TClearIndexFlavor.nb", CopyTag -> None],
   Item["ToFlavor","TToFlavor.nb", CopyTag -> None],
   Item["IndexFlavorQ","TIndexFlavorQ.nb", CopyTag -> None],
   Item["GetIndexFlavor","TGetIndexFlavor.nb", CopyTag -> None]}],

 BrowserCategory["Index Expansions", None,
  {Item["SumExpansion","TSumExpansion.nb", CopyTag -> None],
   Item["ArrayExpansion","TArrayExpansion.nb", CopyTag -> None],
   Item["EinsteinSum","TEinsteinSum.nb", CopyTag -> None],
   Item["EinsteinArray","TEinsteinArray.nb", CopyTag -> None],
   Item["PartialSum","TPartialSum.nb", CopyTag -> None],
   Item["PartialArray","TPartialArray.nb", CopyTag -> None],
   Item["EinsteinArgument","TEinsteinArgument.nb", CopyTag -> None]}],

 BrowserCategory["Tensor Simplifications & Slots", None,
  {Item["TensorSimplify","TTensorSimplify.nb", CopyTag -> None],
   Item["SimplifyTensorSum","TSimplifyTensorSum.nb", CopyTag -> None],
   Item["PatternReplaceIndex","TPatternReplaceIndex.nb", CopyTag -> None],
   Item["IndexChange","TIndexChange.nb", CopyTag -> None],
   Item["UpDownAdjust","TUpDownAdjust.nb", CopyTag -> None],
   Item["UpDownSwap","TUpDownSwap.nb", CopyTag -> None],
   Item[Delimiter],
   Item["PermuteTensorSlots","TPermuteTensorSlots.nb", CopyTag -> None],
   Item["ExtractTensorSlots","TExtractTensorSlots.nb", CopyTag -> None],
   Item["SlotsToTensor","TExtractTensorSlots.nb", CopyTag -> None],
   Item["ExtractTermSlots","TExtractTermSlots.nb", CopyTag -> None],
   Item["CanonicalUpDowns","TCanonicalUpDowns.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Metric & Curvature", None,
  {Item["MetricSimplify","TMetricSimplify.nb", CopyTag -> None],
   Item["CalculateChristoffels","TCalculateChristoffels.nb", CopyTag -> None],
   Item["CalculateRiemannd","TCalculateRiemannd.nb", CopyTag -> None],
   Item["SetRicciContraction","TSetRicciContraction.nb", CopyTag -> None],
   Item["CalculateRRRG","TCalculateRRRG.nb", CopyTag -> None],
   Item["CalculateWeyldown","TCalculateWeyldown.nb", CopyTag -> None],
   Item["CovariantCommutator","TCovariantCommutator.nb", CopyTag -> None]}],

 Item["OrthonormalTransformation","TOrthonormalTransformation.nb", CopyTag -> None],

 Item[Delimiter],
 BrowserCategory["Kronecker Routines", None,
  {Item["KroneckerEvaluate","TKroneckerEvaluate.nb", CopyTag -> None],
   Item["KroneckerContract","TKroneckerContract.nb", CopyTag -> None],
   Item["FullKroneckerExpand","TFullKroneckerExpand.nb", CopyTag -> None],
   Item["PartialKroneckerExpand","TPartialKroneckerExpand.nb", CopyTag -> None],
   Item["KroneckerAbsorb","TKroneckerAbsorb.nb", CopyTag -> None],
   Item["PermutationPseudotensor","TPermutationPseudotensor.nb", CopyTag -> None],
   Item["PermutationSymbolRule","TPermutationSymbolRule.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Symmetry", None,
  {Item["SymmetrizeSlots","TSymmetrizeSlots.nb", CopyTag -> None],
   Item["SymmetrizePattern","TSymmetrizePattern.nb", CopyTag -> None],
   Item["TensorSymmetry","TTensorSymmetry.nb", CopyTag -> None],
   Item["DeclarePatternSymmetries","TDeclarePatternSymmetries.nb", CopyTag -> None],
   Item["Symmetric","TSymmetric.nb", CopyTag -> None],
   Item["AntiSymmetric","TAntiSymmetric.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["CircleTimes & Slots", None,
  {Item["CircleTimes","TCircleTimes.nb", CopyTag -> None],
   Item["CircleEvalRule","TCircleEvalRule.nb", CopyTag -> None],
   Item["EvaluateSlots","TEvaluateSlots.nb", CopyTag -> None],
   Item["BasisDotProductRules","TBasisDotProductRules.nb", CopyTag -> None],
   Item["ReverseBasisDotProductRules","TReverseBasisDotProductRules.nb", CopyTag -> None],
   Item["EvaluateDotProducts","TEvaluateDotProducts.nb", CopyTag -> None],
   Item["ConstructDirectProduct","TConstructDirectProduct.nb", CopyTag -> None],
   Item["GenerateBasisTensors","TGenerateBasisTensors.nb", CopyTag -> None]}],

 BrowserCategory["Arrays", None,
  {Item["ToArrayValues","TToArrayValues.nb", CopyTag -> None],
   Item["ContractArray","TContractArray.nb", CopyTag -> None],
   Item["DotTensorFactors","TDotTensorFactors.nb", CopyTag -> None],
   Item["ExpandDotArray","TExpandDotArray.nb", CopyTag -> None],
   Item["DotOperate","TDotOperate.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Coordinates", None,
  {Item["UseCoordinates","TUseCoordinates.nb", CopyTag -> None],
   Item["CoordinatesToTensors","TCoordinatesToTensors.nb", CopyTag -> None]}],

 BrowserCategory["Derivatives", None,
  {Item["PartialD","TPartialD.nb", CopyTag -> None],
   Item["ExpandPartialD","TExpandPartialD.nb", CopyTag -> None],
   Item["NondependentPartialD","TNondependentPartialD.nb", CopyTag -> None],
   Item["UsePartialDChainRule","TUsePartialDChainRule.nb", CopyTag -> None],
   Item[Delimiter],
   Item["CovariantD","TCovariantD.nb", CopyTag -> None],
   Item["ExpandCovariantD","TExpandCovariantD.nb", CopyTag -> None],
   Item["SetScalarSingleCovariantD","TSetScalarSingleCovariantD.nb", CopyTag -> None],
   Item["BasisExpandCovariantD","TBasisExpandCovariantD.nb", CopyTag -> None],
   Item[Delimiter],
   Item["TotalD","TTotalD.nb", CopyTag -> None],
   Item["ExpandTotalD","TExpandTotalD.nb", CopyTag -> None],
   Item["UseTotalDChainRule","TUseTotalDChainRule.nb", CopyTag -> None],
   Item["ReversePartialTotalChainRule","TReversePartialTotalChainRule.nb", CopyTag -> None],
   Item[Delimiter],
   Item["AbsoluteD","TAbsoluteD.nb", CopyTag -> None],
   Item["ExpandAbsoluteD","TExpandAbsoluteD.nb", CopyTag -> None],
   Item[Delimiter],
   Item["LieD","TLieD.nb", CopyTag -> None],
   Item["ExpandLieD","TExpandLieD.nb", CopyTag -> None]}],

 Item[Delimiter],
 BrowserCategory["Functions & Rules", None,
  {Item["LinearBreakout","TLinearBreakout.nb", CopyTag -> None],
   Item["PushOnto","TPushOnto.nb", CopyTag -> None],
   Item["MapLevelParts","TMapLevelParts.nb", CopyTag -> None],
   Item["MapLevelPatterns","TMapLevelPatterns.nb", CopyTag -> None],
   Item["UnnestTensor","TUnnestTensor.nb", CopyTag -> None],
   Item["SymbolsToPatterns","TSymbolsToPatterns.nb", CopyTag -> None],
   Item["LHSSymbolsToPatterns","TLHSSymbolsToPatterns.nb", CopyTag -> None],
   Item["HoldOp","THoldOp.nb", CopyTag -> None],
   Item["EvaluateAtPattern","TEvaluateAtPattern.nb", CopyTag -> None]}]
}]
