(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<Local`SrednickiInit`


DefPrint["p92L0",Subscript[\[ScriptCapitalL], 0]->-(1/2)PartialD[\[CurlyPhi][x[n]],\[Mu]]PartialD[\[CurlyPhi][x[n]],\[Nu]]guu[\[Mu],\[Nu]]
-1/2 m^2 \[CurlyPhi][x[n]]\[CurlyPhi][x[n]]
];
DefPrint["e96",Z->Exp[I IntegralOp[{x[n]},Subscript[\[ScriptCapitalL], 1][1/I \[Delta]Op[J[x[n]]]]]].Subscript[Z, 0]];
DefPrint["e97",Subscript[Z, 0]->Exp[I/2 IntegralOp[{x[a],x[b]},J[x[a]]. \[CapitalDelta][x[a]-x[b]].J[x[b]]]]];
DefPrint["p104",Subscript[\[ScriptCapitalL], 1][\[CurlyPhi]_]->HoldForm[1/2 g.\[CurlyPhi].(PartialD[\[CurlyPhi],\[Mu]].PartialD[\[CurlyPhi],\[Nu]].guu[\[Mu],\[Nu]])]];
t96a=e96/.p104/.\[Delta]Op[a_]^\[Dagger]->\[Delta]Op[a^\[Dagger]]/.J[a_]^\[Dagger]->(J^\[Dagger])[a]//ReleaseHold



