(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<Local`SrednickiInit`


"Definitions used for this problem"//CC
Clear[i,n]
DefPrint["e2230",\[ScriptCapitalL][x_]->-guu[\[Alpha][x],\[Beta][x]]xPartialD[\[CurlyPhi][x],\[Alpha][x]].xPartialD[\[CurlyPhi][x],\[Beta][x]]/2-V[\[CurlyPhi][x]]]
DefPrint["sub\[ScriptCapitalL]",x\[ScriptCapitalL][\[CurlyPhi]_,\[Mu]_]->\[ScriptCapitalL][\[CurlyPhi],xPartialD[\[CurlyPhi],\[Mu]]]]
DefPrint["e2206",ju[\[Mu]_][\[CurlyPhi]_,x_]->xPartialD[x\[ScriptCapitalL][\[CurlyPhi][x],\[Mu]],xPartialD[\[CurlyPhi][x],\[Mu]]] \[Delta][\[CurlyPhi][x]]]
subj=e2206/.sub\[ScriptCapitalL]
ju[\[Nu]][\[Psi],y]/.subj;
DefPrint["e2217",Q->IntegralOp[{{x[space@i]}},ju[0][\[CurlyPhi],x]]->IntegralOp[{{x[space@i]}},Im[ddPartialD[(\[CurlyPhi]^\[Dagger])[x],\[CurlyPhi][x],0]]]](* ddPartialD represents dual directional PartialD *)
sub\[CapitalPi]=xPartialD[\[CurlyPhi]_[x_],0]->\[CapitalPi][x]
subConj={Conjugate[Conjugate[a_][x_]]->a[x],Conjugate[a_[x_]]->Conjugate[a][x],Conjugate[xPartialD[a_,b_]]->xPartialD[Conjugate[a],b]}
(*Rules to move [y] variable to end.*)
subCommute={\[CurlyPhi][y].xPartialD[\[CurlyPhi][x],space@a_]->xPartialD[\[CurlyPhi][x],space@a].\[CurlyPhi][y],\[CurlyPhi][y].\[CurlyPhi][x]->\[CurlyPhi][x].\[CurlyPhi][y],
\[CapitalPi][y].\[CapitalPi][x]->\[CapitalPi][x].\[CapitalPi][y],\[CurlyPhi][y_].\[CapitalPi][x_]->\[CapitalPi][x].\[CurlyPhi][y]+I DiracDelta[space@x-space@y]};
subCommutex={subCommute,
\[CurlyPhi][y].(\[CurlyPhi]^\[Dagger])[x]->(\[CurlyPhi]^\[Dagger])[x].\[CurlyPhi][y],
\[CurlyPhi][y].\[CapitalPi][x]->\[CapitalPi][x].\[CurlyPhi][y]+I DiracDelta[space@x-space@y],\[CurlyPhi][y].(\[CapitalPi]^\[Dagger])[x]->(\[CapitalPi]^\[Dagger])[x].\[CurlyPhi][y]+I DiracDelta[space@x-space@y],
V[\[CurlyPhi][y]].V[\[CurlyPhi][x]]->V[\[CurlyPhi][x]].V[\[CurlyPhi][y]],
\[CurlyPhi][y].V[\[CurlyPhi][x]]->V[\[CurlyPhi][x]].\[CurlyPhi][y],
xPartialD[\[CurlyPhi][y],space@y].V[\[CurlyPhi][x]]->V[\[CurlyPhi][x]].xPartialD[\[CurlyPhi][y],space@y],
xPartialD[\[CurlyPhi][y],a_].xPartialD[\[CurlyPhi][x],b_]:>If[Head[a]===space&&Head[b]===space,xPartialD[\[CurlyPhi][x],b].xPartialD[\[CurlyPhi][y],a],xPartialD[\[CurlyPhi][y],a].xPartialD[\[CurlyPhi][x],b]],
\[CurlyPhi][y].xPartialD[\[CurlyPhi][x],a_]:>If[Head[a]===space,xPartialD[\[CurlyPhi][x],a].\[CurlyPhi][y],xPartialD[\[CurlyPhi][x],a].\[CurlyPhi][y]+I DiracDelta[space@x-space@y]]
}//Flatten
DefPrint["e328",{\[CurlyPhi][y].\[CurlyPhi][x]->\[CurlyPhi][x].\[CurlyPhi][y],\[CapitalPi][y].\[CapitalPi][x]->\[CapitalPi][x].\[CapitalPi][y],\[CurlyPhi][y].\[CapitalPi][x]->\[CapitalPi][x].\[CurlyPhi][y]+I DiracDelta[space@x-space@y]}]
DefPrint["e322",xPartialD[\[ScriptCapitalL][\[CurlyPhi][x_],xPartialD[\[CurlyPhi][x_],\[Mu]_]],xPartialD[\[CurlyPhi][x_],0]]->\[CapitalPi][x]]
DefPrint["e2231",Tuu[\[Mu]_,\[Nu]_][x_]->-guu[\[Mu],\[Alpha][x]]xPartialD[\[CurlyPhi][x],\[Alpha][x]].xPartialD[\[CurlyPhi][x],\[Nu]] +guu[\[Mu],\[Nu]] \[ScriptCapitalL][x]]
DefPrint["e2235",Pu[\[Mu]_]->IntegralOp[{{space@x}},Tuu[0,\[Mu]][x]]]
dotRetainList={xPartialD[_,_],\[CurlyPhi][_],(\[CurlyPhi]^\[Dagger])[_],\[CapitalPi][_],\[ScriptCapitalL][_],V[_]}
sepTX=xPartialD[a_,b_]:>If[Head[b]=!=space,-xPartialD[a,0]+xPartialD[a,space@b],xPartialD[a,b]]

subCommuteP={};

nDot[n_,a_]:=Apply[Dot,Table[a,{i,n}]]

inPartialDot=a___.xPartialD[b_,y_].c___->xPartialD[a.b.c,y]

gatherPartialD={-xPartialD[b_,y_]->xPartialD[-b,y],xPartialD[a_,y_]+xPartialD[b_,y_]->xPartialD[a+b,y]}

sumguu={d___. xPartialD[\[CurlyPhi][z_],a_].xPartialD[\[CurlyPhi][z_],b_].c___ (guu[a_,b_]|guu[b_,a_]):>If[Head[a]=!=space&&!IntegerQ[a]&&Head[b]=!=space&&!IntegerQ[b],
d.(-xPartialD[\[CurlyPhi][z],0].xPartialD[\[CurlyPhi][z],0]+xPartialD[\[CurlyPhi][z],space@a].xPartialD[\[CurlyPhi][z],space@a]).c,

If[(a==0&&Head[b]=!=space)||(b==0&&Head[a]=!=space),d.(-xPartialD[\[CurlyPhi][z],0].xPartialD[\[CurlyPhi][z],0]).c(* *),

d. xPartialD[\[CurlyPhi][z],a].xPartialD[\[CurlyPhi][z],b].c guu[a,b](*no change*)
]
],
d___. xPartialD[\[CurlyPhi]_,a_].c___ (guu[a_,0]|guu[0,a_]):>d.xPartialD[\[CurlyPhi],0].c,

guu[0,0]->-1}

sumguu0=(*with no space time separation*){d___. xPartialD[\[CurlyPhi][z_],a_].xPartialD[\[CurlyPhi][z_],b_].c___ (guu[a_,b_]|guu[b_,a_]):>If[Head[a]=!=space&&!IntegerQ[a]&&Head[b]=!=space&&!IntegerQ[b],
d.(-xPartialD[\[CurlyPhi][z],a].xPartialD[\[CurlyPhi][z],b]).c guu[a,b],
If[(a==0&&Head[b]=!=space&&!IntegerQ[b])||(b==0&&Head[a]=!=space&&!IntegerQ[a]),d.(-xPartialD[\[CurlyPhi][z],0].xPartialD[\[CurlyPhi][z],0]).c(* *),
d. xPartialD[\[CurlyPhi][z],a].xPartialD[\[CurlyPhi][z],b].c guu[a,b](*no change*)
]
],
d___. xPartialD[\[CurlyPhi]_,a_].c___ (guu[a_,0]|guu[0,a_]):>d.xPartialD[\[CurlyPhi],0].c,

guu[0,0]->-1}

n2230=e2230/.sumguu



