(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Needs["TensorCalculus4V6`Tensorial`"]
Needs["QuantumAlgebra`QuantumAlgebra`"]
Needs["Combinatorica`"]
<<Local`LocalFunctions`
IntegrateSumFunctions


Unprotect[Dot];
Dot[a_,Times[b_,Dot[c_]]]:=Times[b,Dot[a,c]]
Dot[a___,1,c___]:=Dot[a,c]
Dot[a___,0,c___]:=0
Dot[a___,b_+c_,d___]:=Dot[a,b,d]+Dot[a,c,d]
Protect[Dot];


Indices4D={0,1,2,3};
DeclareBaseIndices[{0,1,2,3},{field,{1,2}}]
DeclareIndexFlavor[{field,Red}]
DeclareBaseIndices[Indices4D]
DefineTensorShortcuts[{{x,y,dx,\[Xi],b,r,zero,\[CurlyPhi],\[Psi],\[Psi]c},1},{{x,g,\[Delta] ,\[Sigma],zero,\[Omega],\[Omega]1,\[Omega]2,\[Omega]s,\[Omega]a,\[Eta],\[CapitalLambda],A,B},2},{{\[CapitalGamma],\[Epsilon]},3}]
labels = {x,\[Delta],g, \[CapitalGamma]};
DeclareZeroTensor[zero]
TensorLabelFormat[zero,0]

SetTensorValues[\[Delta]ud[i,j],IdentityMatrix[4]]
\[Delta]ud[i,j];
%//EinsteinArray[]//MatrixForm;
SetTensorValues[\[Eta]ud[i,j],DiagonalMatrix[{-1,1,1,1}]]
SetTensorValues[\[Eta]uu[i,j],DiagonalMatrix[{-1,1,1,1}]]
SetTensorValues[\[Eta]dd[i,j],DiagonalMatrix[{-1,1,1,1}]]
\[Eta]ud[i,j];
\[Eta]array=%//EinsteinArray[];



