(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<Local`QFTToolKit2`
"Local notational definitions";
rghtA[a_]:=Superscript[a,o]
cl[a_]:=Subscript[\[LeftAngleBracket]a\[RightAngleBracket], cl];
clB[a_]:=Subscript[{a}, cl];
ct[a_]:=ConjugateTranspose[a];
cc[a_]:=Conjugate[a];
star[a_]:=Superscript[a,"*"];
cross[a_]:=Superscript[a,"\[Times]"];
deg[a_]:=\[LeftBracketingBar]a\[RightBracketingBar];
it[a_]:=Style[a,Italic]
iD:=it[D]
iA:=it[A]
iI:=it["I"]
C\[Infinity]:=
\!\(\*SuperscriptBox[\(C\), \("\<\[Infinity]\>"\)]\)
Subscript[B, x_]:=T[B,"d",{x}]
Subscript[(("\[Del]")^S), n_]:=T["\!\(\*SuperscriptBox[\(\[Del]\), \(S\)]\)","d",{n}]

accumDef[item_]:=Block[{},$defall=tuAppendUniq[item][$defall];""];
selectDef[heads_,with_:{},all_:Null]:=tuRuleSelect[$defall][Flatten[{heads}]]//Select[#,tuHasAllQ[#,Flatten[{with}]]&]&//If[all===Null,Last[#],#]&;

Clear[expandDC];
expandDC[sub_:{},scalar_:{}]:=tuRepeat[{sub,tuOpDistribute[Dot],tuOpSimplify[Dot,scalar],tuOpDistribute[CircleTimes],tuOpSimplify[CircleTimes,scalar]}];
Clear[expandCom]

expandCom[subs_:{}][exp_]:=Block[{tmp=exp},
tmp=tmp//.tuCommutatorExpand//expandDC[];
tmp=tmp/.toxDot//.Flatten[{subs}];
tmp=tmp//tuMatrixOrderedMultiply//(#/.toDot&)//expandDC[];
tmp
];

Clear[$symmetries]
$symmetries:={tt:T[g,"uu",{\[Mu]_,\[Nu]_}]:>tuIndexSwap[{\[Mu],\[Nu]}][tt]/;OrderedQ[{\[Nu],\[Mu]}],
tt:T[F,"uu",{\[Mu]_,\[Nu]_}]:>-tuIndexSwap[{\[Mu],\[Nu]}][tt]/;OrderedQ[{\[Nu],\[Mu]}],
CommutatorM[a_,b_]:>-CommutatorM[b,a]/;OrderedQ[{b,a}],
CommutatorP[a_,b_]:>CommutatorP[b,a]/;OrderedQ[{b,a}],CommutatorP[T[\[Gamma],"d",{5}],T[\[Gamma],"u",{\[Mu]}]]->0,
tt:T[\[Gamma],"u",{\[Mu]}].T[\[Gamma],"d",{5}] :>-Reverse[tt]
};
$symmetries//ColumnBar


$defall={};(*accumulator for all definitions*)
PR[CO["We use equivalence symbol \[TildeEqual] for isomorphism, and Mod[] symbol for quotient group?"]
]



