(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



hubble:=H->Function[t,a'[t]/a[t]]


\[Kappa]=8\[Pi] G / 3;


friedmann:=H[t]^2==\[Kappa] (a[t]/a0)^2 Subscript[\[Rho], s][t]-kc


raychaudhuri:=H'[t]==-(1/2) H[t]^2 (1+3Subscript[w, s][t])


energycons:=Subscript[\[Rho], s]'[t]==-3H[t]Subscript[\[Rho], s][t](1+Subscript[w, s][t])


BackgroundEq:={friedmann}


BackgroundIC:={a[0]==0}


BackgroundVar:={a[t]}


cons1:=k^2 \[CapitalPhi][t] + 3 H[t](\[CapitalPhi]'[t]+H[t]\[CapitalPsi][t])==-(3/2) H[t]^2 Subscript[\[CapitalDelta], s][t]


cons2:=k (\[CapitalPhi]'[t]+H[t]\[CapitalPsi][t])==3/2 H[t]^2 (1+Subscript[w, s][t]) Subscript[V, s][t]


dyn1:=\[CapitalPhi]''[t]+H[t](\[CapitalPsi]'[t]+2\[CapitalPhi]'[t])+(2H'[t]+H[t]^2)\[CapitalPsi][t]+1/3 k^2 (\[CapitalPhi][t]-\[CapitalPsi][t])==3/2 H[t]^2 (Subscript[c, s][t]Subscript[\[CapitalDelta], s][t]+Subscript[w, s][t]Subscript[\[CapitalGamma], s][t])


dyn2:=k^2 (\[CapitalPhi][t]-\[CapitalPsi][t])==3 H[t]^2 Subscript[w, s][t]Subscript[\[CapitalPi], s][t]


scalvars:={\[CapitalPhi][t],\[CapitalPsi][t]}


auxpot=mkpure[{Subscript[\[Sigma], s][t]->Subscript[h, s,T]'[t]/k-Subscript[B, s][t],Subscript[\[ScriptCapitalR], s][t]->Subscript[h, s,L][t]+Subscript[h, s,T][t]/3}]


vcons:=k^2 Subscript[\[Sigma], V][t]==-6 H[t]^2 (1+Subscript[w, s][t])Subscript[\[CapitalOmega], V][t]


vdyn:=k (Subscript[\[Sigma], V]'[t]+2H[t]Subscript[\[Sigma], V][t])==3H[t]^2 Subscript[w, s][t]Subscript[\[CapitalPi], V][t]


vecvars:={Subscript[\[Sigma], V][t]}


tensor:=Subscript[h, T]''[t]+2H[t]Subscript[h, T]'[t]+k^2 Subscript[h, T][t]==3H[t]^2 Subscript[w, s][t]Subscript[\[CapitalPi], T][t]


tensvars:={Subscript[h, T][t]}


Subscript[w, c][t_]:=0


Subscript[\[Rho], c][t_]:=Subscript[\[Rho], c0] (a[t]/a0)^(-3(1+Subscript[w, c][t]))


Subscript[P, c][t_]:=Subscript[w, c][t] Subscript[\[Rho], c][t]


Subscript[c, c][t_]:=0


Subscript[\[CapitalGamma], c][t_]:=0


cdm1:=Subscript[\[CapitalDelta], c]'[t]==-k Subscript[V, c][t]+3\[CapitalPhi]'[t]


cdm2:=Subscript[V, c]'[t]==-H[t]Subscript[V, c][t]+k \[CapitalPsi][t]


Subscript[\[CapitalPi], c][t_]:=0


cdm:={cdm1,cdm2}


vcdm1:=Subscript[\[CapitalOmega], V,c]'[t]==-H[t]Subscript[\[CapitalOmega], V,c][t]


(*Subscript[\[CapitalOmega], V,c][t_]:=0*)


Subscript[\[CapitalPi], V,c][t_]:=0


vcdmvars={Subscript[\[CapitalOmega], V,c][t]}


Subscript[\[CapitalPi], T,c][t_]:=0


cdmvars:={Subscript[\[CapitalDelta], c][t],Subscript[V, c][t]}


Subscript[w, \[Gamma]][t_]:=1/3


Subscript[\[Rho], \[Gamma]][t_]:=Subscript[\[Rho], \[Gamma]0] (a[t]/a0)^(-3(1+Subscript[w, \[Gamma]][t]))


Subscript[P, \[Gamma]][t_]:=Subscript[w, \[Gamma]][t] Subscript[\[Rho], \[Gamma]][t]


Subscript[c, \[Gamma]][t_]:=Subscript[P, \[Gamma]]'[t]/Subscript[\[Rho], \[Gamma]]'[t]


Subscript[\[CapitalGamma], \[Gamma]][t_]:=0


tauc:=dtight/(a[t]Subscript[n, e][t] Subscript[\[Sigma], T])


photon1:=Subscript[\[CapitalDelta], \[Gamma]]'[t]==-(4/3)k Subscript[V, \[Gamma]][t]+4\[CapitalPhi]'[t]


photon2:=Subscript[V, \[Gamma]]'[t]==k (Subscript[\[CapitalDelta], \[Gamma]][t]/4-Subscript[\[CapitalPi], \[Gamma]][t]/6)+k \[CapitalPsi][t]+(Subscript[V, b][t]-Subscript[V, \[Gamma]][t])/Subscript[\[Tau], c][t]


photon3:=Subscript[\[CapitalPi], \[Gamma]]'[t]==8/5 k Subscript[V, \[Gamma]][t]-9/5 k Subscript[F, \[Gamma]][t,3]-9/10 Subscript[\[CapitalPi], \[Gamma]][t]/Subscript[\[Tau], c][t]


photon4:=Subscript[F, \[Gamma]]'[t,l]==k (l/(2l-1) Subscript[F, \[Gamma]][t,l-1]-(l+1)/(2l+3) Subscript[F, \[Gamma]][t,l+1])-Subscript[F, \[Gamma]][t,l]/Subscript[\[Tau], c][t]


Subscript[\[CapitalPi], \[Gamma]]=Function[{t},3/5 Subscript[F, \[Gamma]][t,2]];


tphoton[0]:=tphoton[1];
tphoton[1]:={photon1,photon2}/.Subscript[F, \[Gamma]][t,2]->0;
tphoton[2]:={photon1,photon2,photon3}/.Subscript[F, \[Gamma]][t,3]->0;
tphoton[ll_/;ll>2]:=Flatten[{photon1,photon2,photon3,photon4/.Table[{l->x},{x,3,ll}]}]/.Subscript[F, \[Gamma]][t,ll+1]->0;


photonvars:={Subscript[\[CapitalDelta], \[Gamma]][t],Subscript[V, \[Gamma]][t]}


vphoton1:=Subscript[F, \[Gamma],1]'[t]==-k Sqrt[3]/5 Subscript[F, \[Gamma],2][t]+4(Subscript[\[CapitalOmega], V,b][t]-Subscript[\[CapitalOmega], V,\[Gamma]][t])/Subscript[\[Tau], c][t]


vphoton2:=Subscript[F, \[Gamma],2]'[t]==k (Sqrt[3]/3 Subscript[F, \[Gamma],l-1][t]-Sqrt[8]/7 Subscript[F, \[Gamma],l+1][t])-4/Sqrt[3] k Subscript[\[Sigma], V][t]-9/10 Subscript[F, \[Gamma],2][t]/Subscript[\[Tau], c][t]


vphoton3:=Subscript[F, \[Gamma],l]'[t]==k (Sqrt[l^2-1]/(2l-1) Subscript[F, \[Gamma],l-1][t]-Sqrt[(l+1)^2-1]/(2l+3) Subscript[F, \[Gamma],l+1][t])-Subscript[F, \[Gamma],l][t]/Subscript[\[Tau], c][t]


vphotpert:={Subscript[\[CapitalOmega], V,\[Gamma]][t]==1/4 Subscript[F, \[Gamma],1][t],Subscript[\[CapitalPi], V,\[Gamma]][t]==(2Sqrt[3])/5 Subscript[F, \[Gamma],2][t]}


vphotinvert=mkpure[Flatten[{Solve[vphotpert[[1]],Subscript[F, \[Gamma],1][t]],Solve[vphotpert[[2]],Subscript[F, \[Gamma],2][t]]}]];


vphot[2]:=Flatten[({vphoton1,vphoton2}/.{Subscript[F, \[Gamma],3][t]->0}/.vphotinvert)]
vphot[ll_/;ll>2]:=Flatten[({vphoton1,vphoton2,vphoton3/.Table[{l->x},{x,3,ll}]}vphotinvert)]/.{Subscript[F, \[Gamma],ll+1][t]->0}


vpvars:={Subscript[\[CapitalOmega], V,\[Gamma]][t]}


vphotonvars[ll_/;ll>0]:=Flatten[{vpvars,Table[Subscript[F, \[Gamma],x][t],{x,3,ll}]}]


Subscript[\[CapitalPi], T,\[Gamma]][t_]:=0


Subscript[w, b][t_]:=0


Subscript[\[Rho], b][t_]:=Subscript[\[Rho], b0] (a[t]/a0)^(-3(1+Subscript[w, b][t]))


Subscript[P, b][t_]:=Subscript[w, b][t] Subscript[\[Rho], b][t]


Subscript[c, b][t_]:=0


Subscript[\[CapitalGamma], b][t_]:=0


R[t_]:=(4Subscript[\[Rho], \[Gamma]][t])/(3Subscript[\[Rho], b][t])


baryon1:=Subscript[\[CapitalDelta], b]'[t]==-k Subscript[V, b][t]+3\[CapitalPhi]'[t]


baryon2:=Subscript[V, b]'[t]==-H[t]Subscript[V, b][t]+Subscript[c, b][t]^2 k Subscript[\[CapitalDelta], b][t]+R[t](Subscript[V, \[Gamma]][t]-Subscript[V, b][t])/Subscript[\[Tau], c][t]+k \[CapitalPsi][t]-1/2 k R[t](Subscript[w, \[Gamma]][t] Subscript[s, B]-1/2 Subscript[d, B])


baryon:={baryon1,baryon2}


baryonvars:={Subscript[\[CapitalDelta], b][t],Subscript[V, b][t]}


Subscript[\[CapitalPi], b][t_]:=0


vbaryon1:=Subscript[\[CapitalOmega], V,b]'[t]==-H[t]Subscript[\[CapitalOmega], V,b][t]+R[t](Subscript[\[CapitalOmega], V,\[Gamma]][t]-Subscript[\[CapitalOmega], V,b][t])/Subscript[\[Tau], c][t]-3/8 k R[t]Subscript[w, \[Gamma]][t] Subscript[s, V,B]


Subscript[\[CapitalPi], V,b][t_]:=0


vbaryonvars:={Subscript[\[CapitalOmega], V,b][t]}


Subscript[\[CapitalPi], T,b][t_]:=0


tight1:=Subscript[V, b][t]==Subscript[V, \[Gamma]][t]


tight2:=Refine[Eliminate[{photon2,baryon2},{Subscript[\[Tau], c][t]}],{a[t]>0,Subscript[\[Rho], b][t]!=0}]/.{Subscript[V, b]->Subscript[V, \[Gamma]],Subscript[F, \[Gamma]][t,2]->0}


tight:={photon1, baryon1,tight1,tight2}


btightsub:=Subscript[\[Tau], c][t]->(1+R[t]) (Subscript[V, b][t]-Subscript[V, \[Gamma]][t])/(k (Subscript[\[CapitalPi], \[Gamma]][t]/6-Subscript[\[CapitalDelta], \[Gamma]][t]/4)-H[t]Subscript[V, b][t])


bettertight:=Simplify[{baryon1,baryon2,photon1,tight1}//.{btightsub,Subscript[F, \[Gamma]][t,2]->0}]


btsub1:=Subscript[V, b]->Function[{t},Subscript[V, \[Gamma]][t]+\[Delta]V[t]];btsub2:=Subscript[V, \[Gamma]]->Function[{t},Subscript[V, b][t]-\[Delta]V[t]]


btsub3=Flatten[Solve[photon2/.btsub1,\[Delta]V[t]]]/.btsub2


btsub4=Solve[Refine[Eliminate[{photon2,baryon2},{Subscript[\[Tau], c][t]}],{a[t]>0,Subscript[\[Rho], b][t]!=0,a0>0}]/.btsub2,Subscript[V, b]'[t]]


btsub5=Simplify[btsub3/.btsub4]


bteq:=FullSimplify[baryon2/.btsub2/.btsub5/.\[Delta]V'[t]->0]


trsub=Subscript[\[Rho], \[Gamma]0]->3R Subscript[\[Rho], b0]a[t]/(4 a0);


bettertight2:=Simplify[Flatten[{baryon1,bteq,photon1,tight1}]//.{Subscript[F, \[Gamma]][t,2]->0}]


vtight1:=Subscript[\[CapitalOmega], V,b][t]==Subscript[\[CapitalOmega], V,\[Gamma]][t]


vtight2:=Refine[Eliminate[{vphoton1,vbaryon1}/.vphotinvert,{Subscript[\[Tau], c][t]}],{a[t]>0,Subscript[\[Rho], b][t]!=0}]/.{Subscript[\[CapitalOmega], V,b]->Subscript[\[CapitalOmega], V,\[Gamma]],Subscript[F, \[Gamma],2][t]->0,Subscript[\[CapitalPi], V,\[Gamma]][t]->0}


vtight:={vtight1,vtight2}


Subscript[w, \[Nu]][t_]:=1/3


Subscript[\[Rho], \[Nu]][t_]:=Subscript[\[Rho], \[Nu]0] (a[t]/a0)^-4


Subscript[P, \[Nu]][t_]:=Subscript[w, \[Nu]][t]Subscript[\[Rho], \[Nu]][t]


Subscript[c, \[Nu]][t_]:=1/3


Subscript[\[CapitalGamma], \[Nu]][t_]:=0


slnu1:=Subscript[F, \[Nu],0]'[t]==-(k/3)Subscript[F, \[Nu],1][t]+4\[CapitalPhi]'[t]


slnu2:=Subscript[F, \[Nu],1]'[t]==k/5 (5Subscript[F, \[Nu],0][t]-2Subscript[F, \[Nu],2][t])+4k \[CapitalPsi][t]


slnu3:=Subscript[F, \[Nu],l]'[t]==k (l/(2l-1) Subscript[F, \[Nu],l-1][t]-(l+1)/(2l+3) Subscript[F, \[Nu],l+1][t])


slnupert:={Subscript[\[CapitalDelta], \[Nu]][t]==Subscript[F, \[Nu],0][t],Subscript[V, \[Nu]][t]==1/4 Subscript[F, \[Nu],1][t],Subscript[\[CapitalPi], \[Nu]][t]==3/5 Subscript[F, \[Nu],2][t]}


lnuinvert=mkpure[Flatten[{Solve[slnupert[[1]],Subscript[F, \[Nu],0][t]],Solve[slnupert[[2]],Subscript[F, \[Nu],1][t]],Solve[slnupert[[3]],Subscript[F, \[Nu],2][t]]}]];


slnu[0]:=slnu[1];
slnu[1]:=Flatten[({slnu1,slnu2}/.{Subscript[F, \[Nu],2][t]->0}//.lnuinvert)]
slnu[ll_/;ll>1]:=Flatten[({slnu1,slnu2,slnu3/.Table[{l->x},{x,2,ll}]}//.lnuinvert)]/.{Subscript[F, \[Nu],ll+1][t]->0}


slnvars:={Subscript[\[CapitalDelta], \[Nu]][t],Subscript[V, \[Nu]][t],Subscript[\[CapitalPi], \[Nu]][t]}


slnuvars[0]:=slnuvars[1];
slnuvars[ll_/;ll>0]:=Flatten[{slnvars,Table[Subscript[F, \[Nu],x][t],{x,3,ll}]}]


vlnu1:=Subscript[F, \[Nu],1]'[t]==-k Sqrt[3]/5 Subscript[F, \[Nu],2][t]


vlnu2:=Subscript[F, \[Nu],2]'[t]==k (Sqrt[3]/3 Subscript[F, \[Nu],1][t]-Sqrt[8]/7 Subscript[F, \[Nu],3][t])-4/Sqrt[3] k Subscript[\[Sigma], V][t]


vlnu3:=Subscript[F, \[Nu],l]'[t]==k (Sqrt[l^2-1]/(2l-1) Subscript[F, \[Nu],l-1][t]-Sqrt[(l+1)^2-1]/(2l+3) Subscript[F, \[Nu],l+1][t])


vlnupert:={Subscript[\[CapitalOmega], V,\[Nu]][t]==1/4 Subscript[F, \[Nu],1][t],Subscript[\[CapitalPi], V,\[Nu]][t]==(2Sqrt[3])/5 Subscript[F, \[Nu],2][t]}


vlnuinvert=mkpure[Flatten[{Solve[vlnupert[[1]],Subscript[F, \[Nu],1][t]],Solve[vlnupert[[2]],Subscript[F, \[Nu],2][t]]}]];


vlnu[2]:=Flatten[({vlnu1,vlnu2}/.{Subscript[F, \[Nu],3][t]->0}//.vlnuinvert)]
vlnu[ll_/;ll>2]:=Flatten[({vlnu1,vlnu2,vlnu3/.Table[{l->x},{x,3,ll}]}//.vlnuinvert)]/.{Subscript[F, \[Nu],ll+1][t]->0}


vlnvars:={Subscript[\[CapitalOmega], V,\[Nu]][t],Subscript[\[CapitalPi], V,\[Nu]][t]}


vlnuvars[ll_/;ll>0]:=Flatten[{vlnvars,Table[Subscript[F, \[Nu],x][t],{x,3,ll}]}]


tlnu1:=Subscript[F, \[Nu],2]'[t]==-k Sqrt[5]/7 Subscript[F, \[Nu],3][t]-4Subscript[h, T]'[t]


tlnu2:=Subscript[F, \[Nu],l]'[t]==k (Sqrt[l^2-4]/(2l-1) Subscript[F, \[Nu],l-1][t]-Sqrt[(l+1)^2-4]/(2l+3) Subscript[F, \[Nu],l+1][t])


tlnupert:=Subscript[\[CapitalPi], T,\[Nu]][t]==2/5 Subscript[F, \[Nu],2][t]


tlnuinvert=mkpure[Flatten[{Solve[tlnupert,Subscript[F, \[Nu],2][t]]}]];


tlnu[2]:=Flatten[({tlnu1}/.{Subscript[F, \[Nu],3][t]->0}//.tlnuinvert)]
tlnu[ll_/;ll>2]:=Flatten[({tlnu1,tlnu2/.Table[{l->x},{x,3,ll}]}//.tlnuinvert)]/.{Subscript[F, \[Nu],ll+1][t]->0}


tlnvars:={Subscript[\[CapitalPi], T,\[Nu]][t]}


tlnuvars[ll_/;ll>0]:=Flatten[{tlnvars,Table[Subscript[F, \[Nu],x][t],{x,3,ll}]}]


Subscript[f, n0][q_]:=Subscript[g, h]/h^3 1/(Exp[q / (an Subscript[T, n])]+1)


Subscript[w, n][t_]:=1/3 (1-Subscript[m, n]^2 (a[t]/a0)^2)


Subscript[\[Rho], n][t_]:=Subscript[\[Rho], n0] (a[t]/a0)^-4 (1+1/2 Subscript[m, n]^2 (a[t]/a0)^2)


Subscript[P, n][t_]:=1/3 Subscript[\[Rho], n0] (a[t]/a0)^-4 (1-1/2 Subscript[m, n]^2 (a[t]/a0)^2)


Subscript[c, n][t_]:=Normal[Series[Subscript[P, n]'[t]/Subscript[\[Rho], n]'[t],{Subscript[m, n],0,2}]]


Subscript[\[CapitalGamma], n][t_]:=0


snu1:={Subscript[F, n,0]'[t]==-(k/3)(Subscript[F, n,1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,1][t])+4\[CapitalPhi]'[t],
Subscript[G, n,0]'[t]==-(k/3) Subscript[G, n,1][t]+2\[CapitalPhi]'[t]}


snu2:={Subscript[F, n,1]'[t]==k/5 (5(Subscript[F, n,0][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,0][t])-2(Subscript[F, n,2][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,2][t]))+(4+Subscript[m, n]^2 (a[t]/a0)^2)k \[CapitalPsi][t],
Subscript[G, n,1]'[t]==k/5 (5Subscript[G, n,0][t]-2Subscript[G, n,2][t])+2k \[CapitalPsi][t]}


snu3:={Subscript[F, n,l]'[t]==k (l/(2l-1) (Subscript[F, n,l-1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,l-1][t])-(l+1)/(2l+3) (Subscript[F, n,l+1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,l+1][t])),
Subscript[G, n,l]'[t]==k/(2l+1) (l Subscript[G, n,l-1][t]-(l+1) Subscript[G, n,l+1][t])}


snupert:={Subscript[\[CapitalDelta], n][t]==Subscript[F, n,0][t]+1/2 Subscript[m, n]^2 (a[t]/a0)^2 (Subscript[G, n,0][t]-Subscript[F, n,0][t]),
Subscript[V, n][t]==1/4 Subscript[F, n,1][t](1-1/4 Subscript[m, n]^2 (a[t]/a0)^2),
Subscript[\[CapitalPi], n][t]==3/5 (Subscript[F, n,2][t]+1/2 Subscript[m, n]^2 (a[t]/a0)^2 (Subscript[F, n,2][t]- Subscript[G, n,2][t]))}


sninvert:=Flatten[{mkpure[Solve[snupert[[1]],Subscript[F, n,0][t]]],mkpure[Solve[snupert[[2]],Subscript[F, n,1][t]]],mkpure[Solve[snupert[[3]],Subscript[F, n,2][t]]]}]


divsub:=Subscript[G, n,l_]:>Function[{t},Evaluate[(Subscript[G, n,l][t]/(a[t]/a0)^2)]]


tmassive[0]:=tmassive[1];
tmassive[1]:=Flatten[{mnnu1,mnnu2,mnpert}/.divsub]/.{Subscript[F, n,2][t]->0,Subscript[G, n,2][t]->0}
tmassive[ll_/;ll>1]:=Flatten[{mnnu1,mnnu2,mnnu3/.Table[{l->x},{x,2,ll}],mnpert}/.divsub]/.{Subscript[F, n,ll+1][t]->0,Subscript[G, n,ll+1][t]->0}


tmassivealt[0]:=tmassivealt[1];
tmassivealt[1]:=Flatten[({mnnu1,mnnu2}/.{Subscript[F, n,2][t]->0,Subscript[G, n,2][t]->0}//.mninvert)/.divsub]
tmassivealt[ll_/;ll>1]:=Flatten[({mnnu1,mnnu2,mnnu3/.Table[{l->x},{x,2,ll}]}//.mninvert)/.divsub]/.{Subscript[F, n,ll+1][t]->0,Subscript[G, n,ll+1][t]->0}


fdsub:=Subscript[G, n,l_]->Function[t,Subscript[F, n,l][t]/2]


fdinvert=mkpure[Flatten[{Solve[snupert[[1]]/.fdsub,Subscript[F, n,0][t]],Solve[snupert[[2]]/.fdsub,Subscript[F, n,1][t]],Solve[snupert[[3]]/.fdsub,Subscript[F, n,2][t]]}]];


sfnu[0]:=sfnu[1];
sfnu[1]:=Flatten[({snu1[[1]],snu2[[1]]}/.{Subscript[F, n,2][t]->0}/.fdsub//.fdinvert)]
sfnu[ll_/;ll>1]:=Flatten[({snu1[[1]],snu2[[1]],snu3[[1]]/.Table[{l->x},{x,2,ll}]}/.fdsub//.fdinvert)]/.{Subscript[F, n,ll+1][t]->0}


snvars:={Subscript[\[CapitalDelta], n][t],Subscript[V, n][t],Subscript[\[CapitalPi], n][t]}


tmassivevars[0]:=tmassivevars[1];
tmassivevars[ll_/;ll>0]:=Flatten[{snvars,Table[{Subscript[F, n,x][t],Subscript[G, n,x][t]},{x,0,ll}]}]


tmassivealtvars[0]:=tmassivevars[1];
tmassivealtvars[ll_/;ll>0]:=Flatten[{snvars,Table[Subscript[F, n,x][t],{x,3,ll}],Table[Subscript[G, n,x][t],{x,0,ll}]}]


sfnuvars[0]:=sfnuvars[1];
sfnuvars[ll_/;ll>0]:=Flatten[{snvars,Table[Subscript[F, n,x][t],{x,3,ll}]}]


vnu1:={Subscript[F, n,1]'[t]==-k Sqrt[3]/5 (Subscript[F, n,2][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,2][t]),
Subscript[G, n,1]'[t]==-k Sqrt[3]/5 Subscript[G, n,2][t]}


vnu2:={Subscript[F, n,2]'[t]==k (Sqrt[3]/3 (Subscript[F, n,1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,1][t])-Sqrt[8]/7 (Subscript[F, n,3][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,3][t]))-4/Sqrt[3] k Subscript[\[Sigma], V][t],
Subscript[G, n,2]'[t]==k (Sqrt[3]/3 Subscript[G, n,1][t]-Sqrt[8]/7 Subscript[G, n,3][t])+2/Sqrt[3] k Subscript[\[Sigma], V][t]}


vnu3:={Subscript[F, n,l]'[t]==k (Sqrt[l^2-1]/(2l-1) (Subscript[F, n,l-1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,l-1][t])-Sqrt[(l+1)^2-1]/(2l+3) (Subscript[F, n,l+1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,l+1][t])),
Subscript[G, n,l]'[t]==k (Sqrt[l^2-1]/(2l-1) Subscript[G, n,l-1][t]-Sqrt[(l+1)^2-1]/(2l+3) Subscript[G, n,l+1][t])}


vnupert:={Subscript[\[CapitalOmega], V,n][t]==1/4 Subscript[F, n,1][t](1-1/4 Subscript[m, n]^2 (a[t]/a0)^2),
Subscript[\[CapitalPi], V,n][t]==(2Sqrt[3])/5 (Subscript[F, n,2][t]+1/2 Subscript[m, n]^2 (a[t]/a0)^2 (Subscript[F, n,2][t]- Subscript[G, n,2][t]))}


fdvecsub:=Subscript[G, n,l_]->Function[t,Subscript[F, n,l][t]/2]


fdvecinvert=mkpure[Flatten[{Solve[vnupert[[1]]/.fdvecsub,Subscript[F, n,1][t]],Solve[vnupert[[2]]/.fdvecsub,Subscript[F, n,2][t]]}]];


vfnu[2]:=Flatten[({vnu1[[1]],vnu2[[1]]}/.{Subscript[F, n,3][t]->0}/.fdvecsub//.fdvecinvert)]
vfnu[ll_/;ll>2]:=Flatten[({vnu1[[1]],vnu2[[1]],vnu3[[1]]/.Table[{l->x},{x,3,ll}]}/.fdvecsub//.fdvecinvert)]/.{Subscript[F, n,ll+1][t]->0}


vnvars:={Subscript[\[CapitalOmega], V,n][t],Subscript[\[CapitalPi], V,n][t]}


vfnuvars[ll_/;ll>0]:=Flatten[{vnvars,Table[Subscript[F, n,x][t],{x,3,ll}]}]


tnu1:={Subscript[F, n,2]'[t]==-k Sqrt[5]/7 (Subscript[F, n,3][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,3][t])-4Subscript[h, T]'[t],
Subscript[G, n,2]'[t]==-k Sqrt[5]/7 Subscript[G, n,3][t]+2Subscript[h, T]'[t]}


tnu2:={Subscript[F, n,l]'[t]==k (Sqrt[l^2-4]/(2l-1) (Subscript[F, n,l-1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,l-1][t])-Sqrt[(l+1)^2-4]/(2l+3) (Subscript[F, n,l+1][t]-1/2 Subscript[m, n]^2 (a[t]/a0)^2 Subscript[G, n,l+1][t])),
Subscript[G, n,l]'[t]==k (Sqrt[l^2-4]/(2l-1) Subscript[G, n,l-1][t]-Sqrt[(l+1)^2-4]/(2l+3) Subscript[G, n,l+1][t])}


tnupert:=
Subscript[\[CapitalPi], T,n][t]==2/5 (Subscript[F, n,2][t]+1/2 Subscript[m, n]^2 (a[t]/a0)^2 (Subscript[F, n,2][t]- Subscript[G, n,2][t]))


fdtenssub:=Subscript[G, n,l_]->Function[t,Subscript[F, n,l][t]/2]


fdtensinvert=mkpure[Flatten[{Solve[tnupert/.fdtenssub,Subscript[F, n,2][t]]}]];


tfnu[2]:=Flatten[({tnu1[[1]]}/.{Subscript[F, n,3][t]->0}/.fdtenssub//.fdtensinvert)]
tfnu[ll_/;ll>2]:=Flatten[({tnu1[[1]],tnu2[[1]]/.Table[{l->x},{x,3,ll}]}/.fdtenssub//.fdtensinvert)]/.{Subscript[F, n,ll+1][t]->0}


tnvars:={Subscript[\[CapitalPi], T,n][t]}


tfnuvars[ll_/;ll>0]:=Flatten[{tnvars,Table[Subscript[F, n,x][t],{x,3,ll}]}]


Subscript[w, s][0]=1/3;


\[Zeta][t_]:=\[CapitalPhi][t]+2/(3(1+Subscript[w, s][t])) (\[CapitalPsi][t]+1/H[t] \[CapitalPhi]'[t])


leading[sr:HoldPattern[SeriesData[x_,x0_,cl__List,nmin_,nmax_,den_]],nterm_]:=Module[{nz,ni},nz=Flatten[Position[cl,Except[0],1,Heads->False]];If[nterm<Length[cl],SeriesData[x,x0,Take[cl,Flatten[{1,nz[[nterm]]}]],nmin,nmin+nz[[nterm]],den],sr]]


leadingterm[expr_,nterm_]:=Module[{sr},expr/.HoldPattern[sr:SeriesData[___]]->leading[sr,nterm]]


mkpure[ex_]:=ex/.(f_[x_]->expr_)->(f->Function[{x},expr])


mapply[expr_List,f_:Simplify,arg___]:=Map[mapply[#,f,arg]&,expr];
mapply[HoldPattern[a_ -> b_],f_,arg___]:=a->mapply[b,f,arg];
mapply[HoldPattern[a_ == b_],f_,arg___]:=mapply[a-b,f,arg]==0;
mapply[HoldPattern[SeriesData[a_,b_,ls_List,c_,d_,e_]],f_,arg___]:=SeriesData[a,b,mapply[ls,f,arg],c,d,e];
mapply[expr_,f_,arg___]:=f[Sequence@@{expr,arg}];


msimp2[expr_,ex:{x_,x0_,n_}]:=mapply[expr,Simplify[Normal[Series[#,ex]]]&]


$Assumptions=Flatten[{G>0,H0>0,a0>0,\[Omega]>0,splist[Subscript[\[CapitalOmega], #]>0&],Rc>=0,Rb>=0,k>0,omm>0}];


antsub:={Subscript[\[Rho], b0] ->3Rb  Subscript[\[CapitalOmega], m] H0^2/(8\[Pi] G ),Subscript[\[Rho], c0] ->3Rc  Subscript[\[CapitalOmega], m] H0^2/(8\[Pi] G ), Subscript[\[Rho], \[Gamma]0]->3R\[Gamma]  Subscript[\[CapitalOmega], m]^2 H0^4/(8\[Pi] G  \[Omega]^2),Subscript[\[Rho], \[Nu]0]->3R\[Nu] Subscript[\[CapitalOmega], m]^2 H0^4/(8\[Pi] G  \[Omega]^2),Subscript[\[Rho], n0]->3Rn Subscript[\[CapitalOmega], m]^2 H0^4/(8\[Pi] G  \[Omega]^2),H0->\[Omega] Sqrt[Subscript[\[CapitalOmega], r]]/Subscript[\[CapitalOmega], m],R\[Gamma]->1-R\[Nu]-Rn,Rb->1-Rc}


adiabatic[sp_]:=Module[{h,tail},h=First[sp];tail=sp[[2;;]];splist[Subscript[\[Delta], h][t]/(1+Subscript[w, h][t])==Subscript[\[Delta], #][t]/(1+Subscript[w, #][t])&,tail]]


isocurvature[spl_,sp1_,curv_:\[Zeta]]:=Module[{h,tail,adl},h=First[spl];tail=spl[[2;;]];adl=splist[{Subscript[\[Delta], h]'[0]/(1+Subscript[w, h][0])==Subscript[\[Delta], #]'[0]/(1+Subscript[w, #][0]),Subscript[\[Delta], #][0]==0}&,tail]; Flatten[{adl,Subscript[\[Delta], sp1][0]==1,curv[ts]==0/.ts->Hold[0]}]]


splist[f_,i_:{b,c,\[Gamma]}]:=Map[f,i]


eq2pattern[a_==b_]:=a->b


defvar[i_:{b,c,\[Gamma]}]:=mkpure[
{
Subscript[\[Rho], s][t]->Total[splist[Subscript[\[Rho], #][t]&,i]],
Subscript[P, s][t]->Total[splist[Subscript[P, #][t]&,i]],
Subscript[w, s][t]->Total[splist[Subscript[w, #][t]Subscript[\[Rho], #][t]&,i]]/Subscript[\[Rho], s][t],
Subscript[c, s][t]->Total[splist[(1+Subscript[w, #][t])Subscript[\[Rho], #][t]Subscript[c, #][t]&,i]]/((1+Subscript[w, s][t])Subscript[\[Rho], s][t]),
Subscript[\[CapitalDelta], s][t]->(Total[splist[Subscript[\[Rho], #][t]Subscript[\[CapitalDelta], #][t]&,i]]+Subscript[\[Rho], \[Gamma]][t] Subscript[d, B])/Subscript[\[Rho], s][t],
Subscript[V, s][t]->Total[splist[(Subscript[\[Rho], #][t]+Subscript[P, #][t])Subscript[V, #][t]&,i]]/(Subscript[\[Rho], s][t]+Subscript[P, s][t]),
Subscript[\[Delta], s][t]->(Total[splist[Subscript[\[Rho], #][t]Subscript[\[Delta], #][t]&,i]]+Subscript[\[Rho], \[Gamma]][t] Subscript[d, B])/Subscript[\[Rho], s][t],
Subscript[v, s][t]->Total[splist[(Subscript[\[Rho], #][t]+Subscript[P, #][t])Subscript[v, #][t]&,i]]/(Subscript[\[Rho], s][t]+Subscript[P, s][t]),
Subscript[\[CapitalPi], s][t]->(Total[splist[Subscript[P, #][t]Subscript[\[CapitalPi], #][t]&,i]]+Subscript[P, \[Gamma]][t] Subscript[s, B])/Subscript[P, s][t]/.Subscript[F, \[Gamma]][t,2]->0,
Subscript[\[CapitalGamma], s][t]->Total[splist[Subscript[P, #][t]Subscript[\[CapitalGamma], #][t]+(Subscript[c, #][t]-Subscript[c, s][t])Subscript[\[CapitalDelta], #][t]&,i]],
Subscript[\[CapitalOmega], V][t]->(Total[splist[(Subscript[\[Rho], #][t]+Subscript[P, #][t])Subscript[\[CapitalOmega], V,#][t]&,i]])/(Subscript[\[Rho], s][t]+Subscript[P, s][t]),
Subscript[\[CapitalPi], V][t]->(Total[splist[Subscript[P, #][t]Subscript[\[CapitalPi], V,#][t]&,i]]+Subscript[P, \[Gamma]][t] Subscript[s, V,B])/Subscript[P, s][t]/.Subscript[\[CapitalPi], V,\[Gamma]][t]->0,
Subscript[\[CapitalPi], T][t]->(Total[splist[Subscript[P, #][t]Subscript[\[CapitalPi], T,#][t]&,i]]+Subscript[P, \[Gamma]][t] Subscript[s, T,B])/Subscript[P, s][t]/.Subscript[\[CapitalPi], T,\[Gamma]][t]->0
}
]



symb[sym_,sub_]:=If[TrueQ[sub],sym,Subscript[sym, sub]]


density[sub_:True]:=(symb[\[Delta],sub][t]+3(1+symb[w,sub][t])H[t]Subscript[\[Sigma], s][t]/k)/.auxpot


velocity[sub_:True]:=symb[v,sub][t]-Subscript[h, s,T]'[t]/k/.auxpot


phivar=mkpure[\[CapitalPhi][t]->-Subscript[\[ScriptCapitalR], s][t]+H[t]Subscript[\[Sigma], s][t]/k/.auxpot];


psivar=mkpure[\[CapitalPsi][t]->A[t]-H[t]Subscript[\[Sigma], s][t]/k-Subscript[\[Sigma], s]'[t]/k/.auxpot];


gaugevar[i_:{b,c,\[Gamma]}]:=mkpure[Flatten[
{psivar,phivar,
Subscript[\[CapitalDelta], s][t]->density[s],Subscript[V, s][t]->velocity[s],
eq2pattern[raychaudhuri],eq2pattern[energycons],
eq2pattern[D[raychaudhuri,t]],Subscript[w, s]'[t]->Subscript[\[Rho], s]'[t](Subscript[c, s][t]-Subscript[w, s][t])/Subscript[\[Rho], s][t],
splist[Subscript[\[CapitalDelta], #][t]->density[#]&,i],splist[Subscript[V, #][t]->velocity[#]&,i]}
]
]


fixvar[x_]:=x/.{\[CapitalDelta]->\[Delta],V->v}


cngsub:={Subscript[B, s]->Function[t,0],Subscript[h, s,T]->Function[t,0],Subscript[h, s,L]->\[Phi],A->\[Psi]}


cngvars:={\[Psi][t],\[Phi][t]}


synsub:={Subscript[B, s]->Function[t1,0],A->Function[{t1},0],Subscript[h, s,L]->Function[{t1},h[t1]/6],Subscript[h, s,T]->Function[{t1},-(h[t1]+6\[Eta][t1])/2]}


synvars:={h[t],\[Eta][t]}
