(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Subsubtitle:: *)
(*Find the ratio of the neutrino to radiation energy density,  Subscript[f, \[Nu]]  (6.5).  Assume that there are three species of massless neutrinos.*)


<<Dodelson`CommonParameters`
<<Dodelson`DodelsonDefine`
<<Dodelson`LocalFunctions`


(* ::Text:: *)
(*In the early universe before there were significant amounts of matter and matter annihilation, the photon and neutrino temperatures were the same and their respective  energy densities are given by:*)


(* ::Input:: *)
(*Eqn269*)
(*%//ReleaseHold*)
(*Eqn279*)
(*%//ReleaseHold*)


(* ::Text:: *)
(*For the neutrino energy density we use the condition that m<<p, so we set m->0.*)
(*which contains the Zeta function and evaluates to:*)


(* ::Input:: *)
(*rhonu=tmp=Refine[Subscript[\[Rho], \[Nu]][T,0] ,T>0]*)


(* ::Text:: *)
(*The Zeta function satisfies the relationship and the energy density for 3 generations of neutrinos:*)


(* ::Input:: *)
(*Zeta[s]==1 /((1-2^(1-s))Gamma[s]) \!\( *)
(*\*SubsuperscriptBox[\(\[Integral]\), \(0\), \(\[Infinity]\)]*)
(*FractionBox[*)
(*SuperscriptBox[\(t\), \(s - 1\)], \( *)
(*\*SuperscriptBox[\(\[ExponentialE]\), \(t\)] + 1\)] \[DifferentialD]t\)/;Re[s]>0*)
(*rhonu3=3 rhonu*)


(* ::Text:: *)
(*So the ratio of the neutrino to radiation energy density is:*)


(* ::Input:: *)
(*rhonu3/(Subscript[\[Rho], \[Gamma]][T]+rhonu3)*)
