(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)

\!\(\*
  RowBox[{\($UserBaseDirectory;\), "\n", \(Needs["\<TGeneralRelativity1`GeneralRelativity`\>"]\), "\n", \(GRRelations;\), "\n", \(<< Dodelson`Functions`\), "\[IndentingNewLine]", \($ContextPath;\), "\n", \(DeclareBaseIndices[{0, 1, 2, 3}];\), "\[IndentingNewLine]", \(ClearTensorValues[{guu[i, j], gdd[i, j], gud[i, j], \[CapitalGamma]udd[i, j, k], \[CapitalGamma]ddd[i, j, k]}];\), "\n", \(ClearTensorShortcuts[{{\[Phi], F, dF, df}, 0}, {{dP}, 1}];\), "\n", \(ClearTensorShortcuts[{{x, dx, \[Xi], k}, 1}, {{\[Xi], \[Eta], g, h, G, H, \[Delta], \[CapitalLambda], L, R, T, T0}, 2}, {{\[Xi], h, H, \[CapitalGamma]}, 3}, {{R, g, h, H, \[Eta]}, 4}];\), "\n", \(ClearAll[guu, gdd, \[CapitalGamma]udd, \[CapitalGamma]ddd]\), "\n", \(Clear[phi, dphi, \[Phi], \[Epsilon], w, dF, V, VV, i, j, k, l, m, n, J, K, L, M];\), "\n", \(DeclareIndexFlavor[{red, Red}];\), "\n", \(DefineTensorShortcuts[{{x, dx, \[Xi], k}, 1}, {{\[Xi], \[Eta], g, h, G, H, \[Delta], \[CapitalLambda], L, R, T, T0}, 2}, {{\[Xi], h, H, \[CapitalGamma]}, 3}, {{R, g, h, H, \[Eta]}, 4}];\), "\n", \(labs = {x, \[Delta], g, \[CapitalGamma]};\), "\n", \(DeclareTensorSymmetries[g, 2, {1, {1, 2}}];\), "\n", \(SetTensorValues[\[Delta]ud[\[Alpha], \[Beta]], IdentityMatrix[4]];\), "\n", "\n", \(dvB[i_] := Tensor[B[xu[j]], {Void}, {Dif[i]}];\), "\n", \(SetTensorValues[hdd[i, j]\ , \[IndentingNewLine]{\ \[IndentingNewLine]{\ \(-1\) - 2\ A[xu[k]], \(-2\)\ a[xu[0]]\ dvB[1], \(-2\)\ a[xu[0]]\ dvB[2]\ , \(-2\)\ a[xu[0]]\ dvB[3]}\ , \[IndentingNewLine]{\(-2\)\ a[xu[0]]\ dvB[1]\ , a[xu[0]]\^2, 0, 0}, \[IndentingNewLine]{\(-2\)\ a[xu[0]]\ dvB[2]\ , \ 0, a[xu[0]]\^2, 0}, \[IndentingNewLine]{\(-2\)\ a[xu[0]]\ dvB[3]\ , \ 0, 0, a[xu[0]]\^2}\[IndentingNewLine]}]\), "\n", \(metric = hdd[i, j] // EinsteinArray[];\), "\n", \(SetMetricValueRules[g, metric];\), "\n", \(SetChristoffelValueRules[xu[i], metric, \[CapitalGamma]];\), "\[IndentingNewLine]", "\n", 
    RowBox[{"(*", 
      RowBox[{
        StyleBox[\(\(**\)\(**\)\(The\)\),
          FontColor->RGBColor[1, 0, 0]], 
        StyleBox[" ",
          FontColor->RGBColor[1, 0, 0]], 
        StyleBox["setting",
          FontColor->RGBColor[1, 0, 0]], 
        StyleBox[" ",
          FontColor->RGBColor[1, 0, 0]], 
        StyleBox["of",
          FontColor->RGBColor[1, 0, 0]], 
        StyleBox[" ",
          FontColor->RGBColor[1, 0, 0]], \(g\_j\%i\), "rules", " ", "fraught", " ", "with", " ", "pain"}], 
      StyleBox[
        RowBox[{
          StyleBox["**",
            FontColor->RGBColor[1, 0, 0]], "*", ")"}]]}], "\[IndentingNewLine]", \(fGud[i_, j_]\  := \ Module[{tmp}, tmp = guu[i, k]\ gdd[k, j] // EinsteinSum[]; \(tmp /. TensorValueRules[g] // Expand\) // Simplify]\), "\[IndentingNewLine]", \(SetTensorValueRules[\ gud[ii, jj], \ Table[fGud[i, j], {i, 0, 3}, {j, 0, 3}]]\), "\[IndentingNewLine]", "\[IndentingNewLine]", \(fGdu[i_, j_]\  := \ Module[{tmp}, tmp = gdd[i, k]\ guu[k, j] // EinsteinSum[]; \(tmp /. TensorValueRules[g] // Expand\) // Simplify]\), "\[IndentingNewLine]", \(SetTensorValueRules[\ gdu[ii, jj], \ Table[fGdu[i, j], {i, 0, 3}, {j, 0, 3}]]\), "\[IndentingNewLine]", "\[IndentingNewLine]", \(NonzeroValueRules[g] // TableForm;\), "\[IndentingNewLine]", \(Print["\<The spatial flat slice metric\>", metric];\), "\[IndentingNewLine]", "\[IndentingNewLine]", 
    RowBox[{
      RowBox[{"Print", "[", "\"\<\!\(\*
StyleBox[\"Exploring\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"covariant\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivative\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"g\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\>\"", "]"}], ";"}], "\[IndentingNewLine]", \(CovariantD[gdd[i, j], k]\), "\[IndentingNewLine]", \(% // ExpandCovariantD[labs, a]\), "\[IndentingNewLine]", \(tmp = % // ToArrayValues[];\), "\[IndentingNewLine]", \(\(tmp[\([1, 1, 1]\)] // Expand\) // Simplify\), "\[IndentingNewLine]", \(\(tmp[\([1, 1, 2]\)] // Expand\) // Simplify\), "\[IndentingNewLine]", \(\(tmp[\([2, 2, 2]\)] // Expand\) // Simplify\), "\[IndentingNewLine]", \(\(tmp[\([2, 2, 1]\)] // Expand\) // Simplify\), "\[IndentingNewLine]", 
    RowBox[{
      RowBox[{"Print", "[", "\"\<\!\(\*
StyleBox[\"Covariant\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivatives\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"g\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"are\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"not\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"all\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"zero\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\)\>\"", "]"}], ";"}]}]\)



















\!\(\*
  RowBox[{
    RowBox[{"(*", 
      StyleBox[\(FUNCTION\ definitions\),
        FontColor->RGBColor[1, 0, 0]], "*)"}], "\[IndentingNewLine]", "\[IndentingNewLine]", 
    RowBox[{\(ZeroOrder[exp_] := Module[{tmp}, \(\(exp /. TensorValueRules[g]\) /. A[_] \[Rule] 0\) /. Tensor[B[Tensor[__]], List[Void], List[Dif[_]]] \[Rule] 0];\), "\[IndentingNewLine]", "\[IndentingNewLine]", \(ConformalTime[exp_, t_] := Module[{tmp}, tmp = exp /. Tensor[A_, {Void, Void}, {Dif[0], Dif[0]}] -> \(1\/a[\[Eta]]\) Hold[\ TotalD[Tensor[A, {Void}, {Dif[0]}], \[Eta]]\ ]; tmp = tmp /. Tensor[A_, {Void}, {Dif[0]}] -> 1\/a[\[Eta]]\ TotalD[Tensor[A], \[Eta]]\ ; \[IndentingNewLine]tmp = tmp /. \(a'\)[t] \[Rule] \(a'\)[\[Eta]]/a[\[Eta]]; \[IndentingNewLine]tmp = tmp // ReleaseHold; \[IndentingNewLine]tmp = tmp /. t \[Rule] \[Eta]\[IndentingNewLine]];\), "\[IndentingNewLine]", 
      RowBox[{"Print", "[", "\"\<\!\(\*
StyleBox[\"The\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"use\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"total\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivatives\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"here\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"is\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"a\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"weak\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"point\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"in\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"this\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"computation\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\",\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"since\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"it\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"should\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"be\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"a\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"simple\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivative\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"The\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"problem\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"is\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"inconsistency\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"between\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivatives\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"Tensors\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"and\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"simple\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"functions\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", "]"}], "\[IndentingNewLine]", "\[IndentingNewLine]", \(ruleD2 = TotalD[Tensor[p_], {\[Eta], \[Eta]}] -> Tensor[p, {Void, Void}, {Dif[\[Eta]], Dif[\[Eta]]}\ ];\), "\n", \(ruleD1 = TotalD[Tensor[p_], \[Eta]] -> Tensor[p, {Void}, {Dif[\[Eta]]}\ ];\), "\[IndentingNewLine]", "\[IndentingNewLine]", \(TotalEta2Dif[E_] := \ Module[{tmp}, \(E /. ruleD2\) /. ruleD1];\), "\[IndentingNewLine]"}]}]\)



\!\(\*
  RowBox[{\( (*\(**\)\(**\)\(**\)\(**\)*****) \), "\n", 
    RowBox[{\(Clear[phi, dphi, phi0, V, VV, V0, dP, w, dTud, Tud, T0ud, i, j, k, l, m, n];\), "\n", \(SetAttributes[{w}, Constant];\), "\n", "\[IndentingNewLine]", \(VV[x_, y0_] := \(Normal[Series[V[x + y0], {x, 0, 1}]] /. x \[Rule] Tensor[x]\) /. y0 \[Rule] Tensor[y0]\), "\n", \(dphiD[k_] := Tensor[phi, {Void}, {Dif[k]}]\), "\n", \(dphi0D[k_] := Tensor[phi0, {Void}, {Dif[0]}] \[Delta]ud[0, k]\), " ", \( (*\ function\ of\ t\ only\ *) \), "\[IndentingNewLine]", \(phi\  = \ Tensor[phi0] + \ Tensor[w]\ Tensor[dphi];\), " ", "\[IndentingNewLine]", \( (*\ \(phi\  = \ phi0 + \ w\ dphi;\)\ \  ** \ scalar\ definition, \ w\  = \ expansion\ order*) \), "\[IndentingNewLine]", \( (*\ Energy - momentum\ tensor\ \((6.24)\)\ *) \), "\[IndentingNewLine]", \(Tud[i_, j_]\  := \ guu[i, n]\ \ dphiD[n]\ dphiD[j]\  - \ gud[i, j] \((\(1\/2\) guu[m, n]\ dphiD[m]\ dphiD[n]\  + \ VV[dphi, phi0]\ \ )\)\), "\[IndentingNewLine]", \( (*\ remove\ 2  nd\ order\ in\ dphi\ term\ *) \), "\[IndentingNewLine]", \( (*\ somehow\ w\ becomes\ tensor\ *) \), "\n", \(T0ud[i_, j_]\  := \ guu[i, n]\ \ dphi0D[n]\ dphi0D[j]\  - gud[i, j] \((\(1\/2\) guu[m, n]\ dphi0D[m]\ dphi0D[n]\  + \ V[Tensor[phi0]]\ \ )\)\), "\n", 
      RowBox[{"(*", 
        RowBox[{
          RowBox[{
            RowBox[{"--", 
              RowBox[{"-", 
                StyleBox["Following",
                  FontColor->RGBColor[1, 0, 0]]}]}], " ", "method", " ", "in", " ", \(book\ --\)}], "-"}], "*)"}], "\[IndentingNewLine]", \(Print["\<Expression for perturbed energy-momentum tensor to first order.  Metric perturbation contained in g.\>"];\), "\[IndentingNewLine]", \(Tud[i, j];\), "\[IndentingNewLine]", \(T0ud[i, j];\), "\[IndentingNewLine]", \(dTudx = \((Tud[i, j] - T0ud[i, j])\);\), "\[IndentingNewLine]", \(Print["\<Perturbed energy-momentum tensor, dTud[i,j]\>", dTudx];\)}]}]\)







\!\(\*
  RowBox[{\(dTudx // ExpandTensor;\), "\[IndentingNewLine]", \(% // TensorCheck;\), "\[IndentingNewLine]", \(% /. Power[Tensor[w], 2] \[Rule] 0;\), "\[IndentingNewLine]", \(% /. Tensor[w] \[Rule] 1;\), "\[IndentingNewLine]", \(% // Expand;\), "\[IndentingNewLine]", \(% // ConstantTensorDif;\), "\[IndentingNewLine]", \(% // FullForm\ \ ;  (*\ sometimes\ this\ comment\ or\ output\ is\ needed\ for\ following\ to\ work\ *) \[IndentingNewLine]% /. Tensor[phi0, {Void}, {Dif[m_]}] \[Rule] \[Delta]ud[0, m] Tensor[phi0, {Void}, {Dif[0]}\ ];\), "\n", \(% // Expand;\), "\n", \(% // KroneckerAbsorb[\[Delta]];\), "\[IndentingNewLine]", \(tmp1 = % // SymmetrizeSlots[g, 2, {1, {1, 2}}]; \  (*\ this\ statement\ must\ print\ ERROR\ *) \[IndentingNewLine]tmp = \(% // SimplifyTensorSum\) // SymmetrizeSlots[g, 2, {1, {1, 2}}];\), "\[IndentingNewLine]", \(DTud[i_, j_] = tmp;\), "\[IndentingNewLine]", \(Print["\<Perturbed energy-momentum tensor to first order,DTud[i,j]: \>", tmp];\), "\[IndentingNewLine]", \(Print["\<DTud[i,j]=\>", \(DTud[i, j] /. TensorValueRules[g] // Expand\) // Simplify];\), "\[IndentingNewLine]", \(Print["\<DTud[0,0]=\>", tmp = \(DTud[0, 0] // Expand\) // Simplify];\), "\[IndentingNewLine]", \(\(Print["\<=\>", DTud00 = tmp /. TensorValueRules[g] // Simplify];\)\(\[IndentingNewLine]\)
    \), "\[IndentingNewLine]", \(Print["\<DTud[1,0]=\>", DTud[1, 0] /. TensorValueRules[g] // Simplify];\), "\[IndentingNewLine]", \(Print["\<DTud[0,1]=\>", DTud[0, 1] /. TensorValueRules[g] // Simplify];\), "\[IndentingNewLine]", \(Print[\*"\"\<These expressions for DTud[i,j] is consistent with (6.67), (6.68) with added a \!\(g\^\(\(00\)\(\\\ \)\)\)factor.  Note difference between DTud[1,0] and DTud[0,0].\>\""]\), "\[IndentingNewLine]", "\[IndentingNewLine]", 
    RowBox[{
      RowBox[{"Print", "[", 
        RowBox[{"\"\<\!\(\*
StyleBox[\"Check\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"with\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"6.64\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"zero\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"order\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"DTud\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"[\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"1\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\",\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"0\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"]\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"=\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", \(test = ZeroOrder[DTud[1, 0]]\)}], " ", "]"}], ";"}], "\[IndentingNewLine]", \(test = ZeroOrder[test // ArrayExpansion[n]];\), "\[IndentingNewLine]", \(Print[StyleForm["\<Agrees with 6.64 == \>", FontColor \[Rule] Red], test[\([2]\)]];\), "\[IndentingNewLine]", \(testc = CovariantD[test[\([2]\)], 1];\), "\[IndentingNewLine]", 
    RowBox[{
      RowBox[{"Print", "[", 
        RowBox[{"\"\<\!\(\*
StyleBox[\"The\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"covariant\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivative\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"produces\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\>\"", ",", "testc", ",", "\"\<  \!\(\*
StyleBox[\"where\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"only\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"first\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"part\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"last\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"term\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"survives\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"Let\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"us\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"see\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"if\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"this\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"term\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"is\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"produced\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"in\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"full\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"conservation\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"equation\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"below\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\)\>\""}], "]"}], ";"}], "\[IndentingNewLine]", \(ConformalTime[test, xu[0]];\), "\[IndentingNewLine]", \(Print["\<Restate check on 6.64 in conformal time : \>", %[\([2]\)]]\)}]\)























\!\(\*
  RowBox[{
    RowBox[{"(*", 
      RowBox[{
        RowBox[{
          RowBox[{
            RowBox[{"**", 
              RowBox[{"*", " ", 
                StyleBox["This",
                  FontColor->RGBColor[1, 0, 0]], 
                StyleBox[" ",
                  FontColor->RGBColor[1, 0, 0]], 
                StyleBox["next",
                  FontColor->RGBColor[1, 0, 0]], 
                StyleBox[" ",
                  FontColor->RGBColor[1, 0, 0]], 
                StyleBox["portion",
                  FontColor->RGBColor[1, 0, 0]]}]}], 
            StyleBox[",",
              FontColor->RGBColor[1, 0, 0]], 
            StyleBox[" ",
              FontColor->RGBColor[1, 0, 0]], 
            StyleBox[\(straight\ forward\ calculation\ of\ dTud[e, 0]\),
              FontColor->RGBColor[1, 0, 0]], 
            StyleBox[",",
              FontColor->RGBColor[1, 0, 0]], 
            StyleBox["e",
              FontColor->RGBColor[1, 0, 0]]}], 
          StyleBox["]",
            FontColor->RGBColor[1, 0, 0]]}], ",", 
        StyleBox[\(of\ the\ calculation\ is\ an\ exercise\ to\ compare\ with\ 6.69\ and\ 6.71\),
          FontColor->RGBColor[1, 0, 0]]}], " ", "****)"}], "\[IndentingNewLine]", 
    RowBox[{\(tmp0 = CovariantD[DTud[e, 0], e];\), "\[IndentingNewLine]", 
      RowBox[{
        RowBox[{
          StyleBox["Print",
            FontColor->RGBColor[0, 0, 1]], "[", 
          RowBox[{"\"\<\!\(\*
StyleBox[\"Covariant\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivative\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\(\(dT\^e\)\_\(0; e\)\),\nFontColor->RGBColor[1, 0, 0]]\)\>\"", ",", "tmp0"}], "]"}], ";"}], "\[IndentingNewLine]", \(tmp1 = tmp0 //. Tensor[g, List[_, _, Void], List[_, _, Cov[_]]] \[Rule] 0;\), "\[IndentingNewLine]", \(tmp1 = tmp1 //. Tensor[\[Delta], List[_, _, Void], List[_, _, Cov[_]]] \[Rule] 0;\), "\[IndentingNewLine]", 
      RowBox[{
        RowBox[{
          StyleBox["Print",
            FontColor->RGBColor[0, 0, 1]], "[", 
          RowBox[{"\"\<\!\(\*
StyleBox[\"Zero\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"following\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"covariant\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"derivative\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"metric\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\",\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"g\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\",\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"terms\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", \(\((tmp1 - tmp0)\) // Expand\)}], "]"}], ";"}], "\[IndentingNewLine]", \(tmp1 // ExpandTensor;\), "\[IndentingNewLine]", \(tmp2 = tmp1 /. CovariantD[\(\(Derivative[1]\)[V]\)[Tensor[phi0]], e] \[Rule] \(\(Derivative[2]\)[V]\)[Tensor[phi0]] CovariantD[Tensor[phi0], e];\), "\[IndentingNewLine]", \(tmp2 = tmp2 // MetricSimplify[g];\), "\[IndentingNewLine]", 
      RowBox[{
        RowBox[{"Print", "[", 
          RowBox[{"\"\<\!\(\*
StyleBox[\"Replace\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"covariant\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"deriv\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"V\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\>\"", ",", \(\((tmp2 - tmp1)\) // MetricSimplify[g]\)}], "]"}], ";"}], "\[IndentingNewLine]", \(tmp3 = tmp2 // SimplifyTensorSum;\), "\[IndentingNewLine]", "\[IndentingNewLine]", 
      RowBox[{
        RowBox[{
          StyleBox["Print",
            FontColor->RGBColor[0, 0, 1]], "[", "\"\<\!\(\*
StyleBox[\"Substitution\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"for\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"tensor\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"identities\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"phi0\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"(\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"t\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\")\",\nFontColor->RGBColor[1, 0, 0]]\)\>\"", "]"}], ";"}], "\[IndentingNewLine]", \(tmp3 // ExpandCovariantD[labs, f];\), "\[IndentingNewLine]", \(% /. \(PartialD[labs]\)[Tensor[phi0], \ xu[\[Nu]_]\ ] \[Rule] \[Delta]ud[0, \[Nu]] Tensor[phi0, {Void}, {Dif[0]}];\), "\[IndentingNewLine]", \(% /. \(PartialD[labs]\)[Tensor[phi0], \ {xu[0], xu[\[Nu]_]\ }] \[Rule] \[Delta]ud[0, \[Nu]] Tensor[phi0, {Void, Void}, {Dif[0], Dif[0]}];\), "\[IndentingNewLine]", \(covTemp = \(% // Expand\) // KroneckerAbsorb[\[Delta]];\), "\[IndentingNewLine]", \(covTemp // SymmetrizeSlots[\[CapitalGamma], 3, {1, {2, 3}}];\), "\[IndentingNewLine]", \(% // SimplifyTensorSum;\), "\[IndentingNewLine]", \(tmp3 = % // TensorCheck;\), "\[IndentingNewLine]", \( (*\(**\)\(**\)\(**\)\(**\)******) \), "\[IndentingNewLine]", \(tmp4 = tmp3 // PartialToIndices;\), "\[IndentingNewLine]", \(tmp = TensorSpatialFourier[tmp4, dphi, k];\), "\[IndentingNewLine]", \(tmp // Expand;\), "\[IndentingNewLine]", \(% // KroneckerAbsorb[\[Delta]];\), "\[IndentingNewLine]", \(tmp5 = % // MetricSimplify[g];\), "\[IndentingNewLine]", \(dTe0e = % /. ku[0] \[Rule] 0;\), "\[IndentingNewLine]", \(dTe0e = % /. \[CapitalGamma]udu[i_, j_, k_] \[Rule] \[CapitalGamma]udd[i, j, m] guu[k, m];\), "\[IndentingNewLine]", 
      RowBox[{
        RowBox[{"Print", "[", 
          RowBox[{"\"\<\!\(\*
StyleBox[\"The\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"perturbed\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"energy\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"-\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"momentum\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"tensor\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\",\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\(\(dT\^e\)\_\(0; e\)\),\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", "dTe0e"}], "]"}], ";"}], "\[IndentingNewLine]", "\[IndentingNewLine]", 
      RowBox[{"Print", "[", "\"\<\!\(\*
StyleBox[\"Different\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"from\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"book\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"in\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"imaginary\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"terms\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"  \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"Let\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"'\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"s\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"explore\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"these\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"terms\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", "]"}], "\[IndentingNewLine]"}]}]\)



















\!\(\(Print["\<First dFdX[[DTud,i,0],i]\>"];\)\n
  \(DTud[i, 0];\)\n
  \(PartialD[%, i];\)\n
  \(% // SymmetrizeSlots[g, 2, {1, {1, 2}}];\)\n
  \(% // Expand;\)\n
  \(% // MetricSimplify[g];\)\n
  \(tmp = TensorSpatialFourier[%, dphi, k];\)\n
  \(% // Expand;\)\n
  \(% // KroneckerAbsorb[\[Delta]];\)\n
  \(ddTudi0i = % // MetricSimplify[g];\)\n
  \(Print["\<dFdX[DTud[i,0],i]= \>", ddTudi0i];\)\n
  \(Print["\<Note the imaginary terms.\>"];\)\n
  \(\(Print["\<Eliminates terms that = 0:  DFDX[k,i], spatial derivatives of phi0.\>"]\)\(\n\)
  \)\[IndentingNewLine]
  \(rule0 = Tensor[phi0, List[Void, Void], List[Dif[0], Dif[i_]]] -> Tensor[phi0, List[Void, Void], List[Dif[0], Dif[0]]]\ \[Delta]ud[0, i];\)\n
  \(Print["\<Rule: \>", rule0];\)\n
  \(ddTudi0i /. rule0;\)\n
  \(% // KroneckerAbsorb[\[Delta]];\)\n
  \(ddTudi0i = % // SymmetrizeSlots[g, 2, {1, {1, 2}}];\)\n
  \(ddTudi0i = % // MetricSimplify[g, True];\)\n
  \(Print["\<Terms that = 0 : \>", ddTudi0i[\([9, {3, 4}]\)], "\<; \>", ddTudi0i[\([10, {3, 4}]\)]];\)\n
  \(repl = PartialD[guu[_, n], _] kd[n] \[Rule] 0;\)\n
  \(Print["\<Rule: \>", repl];\)\n
  \(ddTudi0i = ddTudi0i /. repl;\)\n
  \(ddTudi0i = ddTudi0i /. kd[0] \[Rule] 0;\)\n
  \(ddTudi0i = ddTudi0i /. ku[0] \[Rule] 0;\)\n
  \(ddTudi0i = ddTudi0i /. ku[i_] kd[i_] \[Rule] k\^2;\)\n
  \(ddTudi0i = ddTudi0i /. PartialD[gud[i_, 0], i_] \[Rule] 0;\)\n
  \(rule2 = PartialD[\(\(Derivative[1]\)[V]\)[Tensor[phi0]], i_] \[Rule] \(\(Derivative[2]\)[V]\)[Tensor[phi0]] PartialD[Tensor[dphi], i];\)\n
  Print["\<Rule: \>", rule2]\n
  \(ddTudi0i = ddTudi0i /. rule2;\)\n
  \(rule3 = PartialD[guu[i_, 0], i_] -> PartialD[guu[0, i], i];\)\n
  Print["\<Rule: symmetry: \>", rule3]\n
  \(ddTudi0i = ddTudi0i /. rule3;\)\n
  \(\(Print[ddTudi0i, "\< <== Intermediate result.  Let's see if the terms involving the derivative of g are significant.\>"]\)\(\n\)
  \)\[IndentingNewLine]
  \(xg000 = \(g000 = ddTudi0i[\([3, 3]\)]\);\)\n
  \(Print["\<Examine \>", g000];\)\n
  \(rule4 = PartialD[guu[0, i_], i_] -> PD[guu[0, i], i];\)\n
  \(g000 = g000 /. rule4;\)\n
  \(g000 = % /. TensorValueRules[g];\)\n
  \(g000 = g000 /. PD \[Rule] PartialD;\)\n
  \(ruleB2 = Power[Tensor[B[Tensor[__]], List[Void], List[Dif[_]]], 2] \[Rule] 0;\)\n
  \(g000 = g000 /. ruleB2;\)\n
  \(xpand = g000[\([2, 1, 1, 2]\)];\)\n
  \(\(Print["\<==>  \>", g000, "\<  order of perturbation, which is to first order \>", PartialD[\(-xpand\), xu[0]]]\)\(\n\)
  \)\[IndentingNewLine]
  \(xg0ii = \(g0ii = ddTudi0i[\([4, 3]\)]\);\)\n
  \(Print["\<Examine \>", g0ii];\)\n
  \(rule4 = PartialD[guu[0, i_], i_] -> PD[guu[0, i], i];\)\n
  \(g0ii = g0ii // SumExpansion[i];\)\n
  \(g0ii = g0ii /. rule4;\)\n
  \(g0ii = % /. TensorValueRules[g];\)\n
  \(ruleB2 = Power[Tensor[B[Tensor[__]], List[Void], List[Dif[_]]], 2] \[Rule] 0;\)\n
  \(g0ii = g0ii /. ruleB2;\)\n
  \(g0ii = g0ii /. PD \[Rule] PartialD;\)\n
  \(Print["\<==>  \>", g0ii, "\<  which is first order in the perturbed quantities.  So to zero order we can neglect terms with derivatives of g.\>"];\)\n
  \(ddTudi0i /. xg000 \[Rule] 0;\)\[IndentingNewLine]
  \(% /. xg0ii \[Rule] 0;\)\[IndentingNewLine]
  \(ddTudi0i = % // MetricSimplify[g];\)\[IndentingNewLine]
  Print["\<dFdX[[DTud,i,0],i]=  \>", ddTudi0i]\[IndentingNewLine]
  \)

































Print["Let's explore the \[CapitalGamma] terms in ==>",dTe0e];
test1=dTe0e[[4,4]];
Print["\!\(\*
  StyleBox[\"We\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"test\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) ",test1];
test1=Tensor[\[CapitalGamma],{0,Void,Void},{Void,0,i}]guu[0,i];
Print["Where we rewrite ==> ",test1];
test1=test1//SumExpansion[i];
test1=%/.TensorValueRules[g,\[CapitalGamma]];
test1=%/.ruleB2;
Print["To 1st order this computes out to = ",test1," <== ",dTe0e[[4,4]]];
test1=dTe0e[[5,4]];
Print["\!\(\*
  StyleBox[\"We\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"test\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) ",test1];
test1=Tensor[\[CapitalGamma],{0,Void,Void},{Void,n,i}]guu[n,i];
Print["Where we rewrite ==> ",test1];
test1=test1//SumExpansion[i,n];
test1=%/.TensorValueRules[g,\[CapitalGamma]];
test1=%/.ruleB2; 
tmp54=test1;
Print["By inspection we set this term varies to 1nd order in perturbation as ==> ",
    test1," <== ",dTe0e[[5,4]]];
test1=dTe0e[[6,4]];
Print["\!\(\*
  StyleBox[\"We\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"test\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) ",test1];
test1=test1/.TensorValueRules[g,\[CapitalGamma]];
test1=%/.ruleB2;
Print["To 1st order this computes out to = ",test1," <== ",dTe0e[[6,4]]];
test1=dTe0e[[7,5]];
Print["\!\(\*
  StyleBox[\"We\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"test\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) ",test1];
test1=test1//ArrayExpansion[n];
test1=%/.TensorValueRules[g,\[CapitalGamma]];
test1=%/.ruleB2;
Print["These terms vary to 1st order in perturbation as ==> ",test1," <== ",
    dTe0e[[7,5]]];
test1=dTe0e[[8,5]];
Print["\!\(\*
  StyleBox[\"We\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"test\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
  StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) ",test1];
test1=Tensor[\[CapitalGamma],{f,Void,Void},{Void,n,i}]guu[n,i];
Print["Where we rewrite ==> ",test1];
test1=test1//SumExpansion[i,n];
test1=test1//ArrayExpansion[f];
test1=%/.TensorValueRules[g,\[CapitalGamma]];
test1=%/.ruleB2;
Print["These terms vary to 1st order in perturbation as ==> ",test1," <== ",
    dTe0e[[8,5]],
    ".  Since this term forms an expression that is dotted with k all these terms are at least 1st order in the perturbation, B, i.e., no 0th order terms." \
];





























\!\(\*
  RowBox[{
    RowBox[{
      RowBox[{"Print", "[", 
        RowBox[{"\"\<\!\(\*
StyleBox[\"We\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"compute\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"to\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"zeroth\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"order\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"dTe0e\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", "dTe0e"}], "]"}], ";"}], "\[IndentingNewLine]", \(test = dTe0e /. ku[i_] kd[i_] \[Rule] kd[i] kd[j] guu[i, j];\), "\[IndentingNewLine]", \(% // EinsteinSum[];\), "\[IndentingNewLine]", \(\(% /. kd[0] \[Rule] 0\) /. ku[0] \[Rule] 0;\), "\[IndentingNewLine]", \(% /. TensorValueRules[g, \[CapitalGamma]];\), "\[IndentingNewLine]", \(test = ZeroOrder[%\ ];\), "\[IndentingNewLine]", \(test = test /. \((kd[1])\)\^2 \[Rule] \ k\^2 - \((kd[2])\)\^2 - \((kd[3])\)\^2 // Expand;\), "\[IndentingNewLine]", \(form = test[\([2, 3]\)];\), "\[IndentingNewLine]", \(eqn669 = Coefficient[test, form];\), "\[IndentingNewLine]", 
    RowBox[{
      RowBox[{"Print", "[", 
        RowBox[{"\"\<\!\(\*
StyleBox[\"The\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"coefficient\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\":\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", "form", ",", "\"\< \!\(\*
StyleBox[\"==\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\">\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", "eqn669"}], "]"}], ";"}], "\[IndentingNewLine]", \(tmp = ConformalTime[eqn669, xu[0]];\), "\[IndentingNewLine]", \(eqn669 /. Tensor[A_, {Void, Void}, {Dif[0], Dif[0]}] -> \(1\/a[\[Eta]]\) Hold[\ TotalD[Tensor[A, {Void}, {Dif[0]}], \[Eta]]\ ];\), "\[IndentingNewLine]", \(% /. Tensor[B_, {Void}, {Dif[0]}] -> 1\/a[\[Eta]]\ TotalD[Tensor[B], \[Eta]]\ ;\), "\[IndentingNewLine]", \(% /. \(a'\)[xu[0]] \[Rule] \(a'\)[\[Eta]]/a[\[Eta]];\), "\[IndentingNewLine]", \(% /. xu[0] \[Rule] \[Eta];\), "\[IndentingNewLine]", \(% // ReleaseHold;\), "\[IndentingNewLine]", \(tmp = tmp \((a[\[Eta]])\)\^2 // Expand;\), "\[IndentingNewLine]", \(tmp = tmp /. \(V''\)[_] \[Rule] 0;\), "\[IndentingNewLine]", 
    RowBox[{
      RowBox[{"Print", "[", 
        RowBox[{"\"\<\!\(\*
StyleBox[\"The\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"coefficient\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"of\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", "form", ",", "\"\< \!\(\*
StyleBox[\"is\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"equal\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"to\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"(\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"6.70\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\")\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"if\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"V\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"''\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"=\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"0\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"and\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"the\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"equation\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"is\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"converted\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"to\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"conformal\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\" \",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\"time\",\nFontColor->RGBColor[1, 0, 0]]\)\!\(\*
StyleBox[\".\",\nFontColor->RGBColor[1, 0, 0]]\) \>\"", ",", "tmp"}], "]"}], ";"}], "\[IndentingNewLine]", "Null"}]\)





































































































