(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Subsubtitle:: *)
(**)


(* ::Text:: *)
(*Inflation also solves the flatness problem.  This is the question of why the energy density today is so close to critical.*)
(*  (a)    Suppose that \[CapitalOmega]==8\[Pi]G\[Rho][t]/(3H^2)  is equal to 0.3 today, where \[Rho] counts the energy density in matter and radiation  (assume zero cosmological constant).   From Eq.1.2, plot \[CapitalOmega]-1  as a function of the scale factor.    How close to one would \[CapitalOmega]  have been back at the Planck epoch (assuming no inflation took place so that the scale factor at the  Planck epoch was of order 10^-32?  This fine-tuning of the initial conditions is the flatness problem.    If not for the fine tuning, an open universe would be obviously open  (i.e.,  \[CapitalOmega]-1 would be almost exactly zero) today.*)
(*(b)    Now show that inflation solve the flatness problem. Extrapolate \[CapitalOmega]-1 back to the end of inflation, and then through 60 e-folds of inflation.*)
(**)


SetDirectory[$HomeDirectory~~"/Mathematica/Dodelson"];
(*
Get["Definition/LegendreFunctions"]
LegendreFunctions
Get["Definition/IntegrateSumFunctions"]
IntegrateSumFunctions
*)
<<Dodelson`DodelsonDefine`
<<Dodelson`CommonParameters`

RecombinationSubs
equalitySubs
ayetaSubs
EnergyDenSubs


(* ::Text:: *)
(*Eqn.1.2, the Hubble parameter defined by the 00-energy-momentum tensor.  The above \[CapitalOmega] relationship becomes:*)


(* ::Input:: *)
(*DefEqn12;*)
(*defe12a;*)
(*defe12a//ReleaseHold;*)
(*tmp=\[CapitalOmega][a]==(8\[Pi] G \[Rho][a])/(3H[a]^2);*)
(*tmp0=Map[#-1&,tmp]*)


(* ::Text:: *)
(*What is value of parameters if \[CapitalOmega][a=1]=.3?*)


(* ::Input:: *)
(*Print["The formula for a==1 : ",*)
(*tmp=tmp0/.\[CapitalOmega][a]->.3/.a->1]*)
(*tmp=tmp//NumericalValues;*)
(*Print["In this case the value of \!\(\*SubscriptBox[\"\[Rho]\", \"0\"]\) is :",*)
(*sub1=Solve[tmp,Subscript[\[Rho], 0]][[1,1]]]*)
(*tmp=tmp0//NumericalValues;*)
(*tmp=tmp/.sub1;*)
(*tmp=Map[Simplify[#]&,tmp];*)
(*tmp[[1]]==Series[tmp[[2]],{a,0,2}]*)
(*Print["This series expansion shows that \[CapitalOmega][a->0] is very near 1 no matter what the current value of \!\(\*SubscriptBox[\"\[CapitalOmega]\", \"m\"]\).  The flatness problem, as I see it, is that this value of \[CapitalOmega][a->0] is unreasonably close to 1."]*)


(* ::Text:: *)
(*This in itself does not seem like a problem since it indicates the early universe was flat regardless of what it is now.*)


(* ::Input:: *)
(*ResetDirectory[]*)
