(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



<<Local`QFTToolKit`
<<Units`
DeclareIndexFlavor[{color,Brown}]
DeclareIndexFlavor[{flavor,Orange}]
AddBaseIndex[{gaugeG,{1,2,3,4,5,6,7,8}}](*SU[3] gauge group index*)
AddBaseIndex[{color,{1,2,3}}](*SU[3] singlet index*)
 AddBaseIndex[{flavor,{1,2,3,4,5,6}}]
(*correspondence: {{u,c,t, with Q=2/3},{d,s,b, with Q=-1/3}}*)


DefineTensorShortcuts[{{\[Phi],v,Y,T,\[Tau],U,D,W,\[Lambda],\[Alpha],g,\[Nu],t,U},1},{{\[Phi],v,\[Tau],Q,d,u,m,CKM,e,t,U,Z},2},{{\[Lambda],Q,U,D,J,t},3},{{U},4}]



